// Code generated by scripts/rebuild_search.go; DO NOT EDIT.
package assets

// SearchWasmHash is the XXH3 hash of the uncompressed search.wasm binary
const SearchWasmHash = "737a2ff3a6dc6dbc"

// SearchSourceHash is the XXH3 hash of the search source code at the time of rebuild
const SearchSourceHash = "0fd43dd7e558e326"
