// Code generated by scripts/rebuild_search.go; DO NOT EDIT.
package assets

// SearchWasmHash is the XXH3 hash of the uncompressed search.wasm binary
const SearchWasmHash = "bb63a6dd268e10f4"

// SearchSourceHash is the XXH3 hash of the search source code at the time of rebuild
const SearchSourceHash = "281b4e05cc7f5981"
