// Code generated by scripts/rebuild_search.go; DO NOT EDIT.
package assets

// SearchWasmHash is the XXH3 hash of the uncompressed search.wasm binary
const SearchWasmHash = "b0b2d4b0bbe5d53d"

// SearchSourceHash is the XXH3 hash of the search source code at the time of rebuild
const SearchSourceHash = "064479a99cf7fbbd"
