package run

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"golang.org/x/sync/errgroup"

	"github.com/Kush-Singh-26/kosh/builder/cache"
	"github.com/Kush-Singh-26/kosh/builder/generators"
	"github.com/Kush-Singh-26/kosh/builder/utils"
	"github.com/spf13/afero"
)

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func shouldGeneratePWAIcons(shouldForce, hasHashFile, hasCache192, hasCache512 bool) bool {
	return shouldForce || !hasHashFile || !hasCache192 || !hasCache512
}

func (b *Builder) generatePWA(ctx context.Context, shouldForce bool) error {
	if b.cfg.IsDev {
		return nil
	}

	g, _ := errgroup.WithContext(ctx)

	g.Go(func() error {
		return generators.GenerateSW(b.Sink, b.cfg.OutputDir, b.cfg.BuildVersion, shouldForce, b.cfg.BaseURL, b.deps.Render.GetAssets())
	})

	g.Go(func() error {
		return generators.GenerateManifest(b.Sink, b.cfg.OutputDir, b.cfg.BaseURL, b.cfg.Title, b.cfg.Description, shouldForce)
	})

	g.Go(func() error {
		iconTimer := utils.StartPhase("PWA icons")
		defer iconTimer.Stop()

		faviconPath := b.getFaviconPath()

		// Ensure info is available
		exists, _ := afero.Exists(b.SourceFs, faviconPath)
		if !exists {
			return nil
		}
		srcInfo, _ := b.SourceFs.Stat(faviconPath)

		// Calculate hash based on favicon mtime and size
		hashContent := fmt.Sprintf("%s-%d-%d", faviconPath, srcInfo.Size(), srcInfo.ModTime().UnixNano())
		currentHash := cache.HashString(hashContent)

		// Check cache
		cacheDir := filepath.Join(b.cfg.CacheDir, "pwa-icons")
		cacheHashFile := filepath.Join(cacheDir, currentHash+".hash")
		cache192 := filepath.Join(cacheDir, currentHash+"-192.png")
		cache512 := filepath.Join(cacheDir, currentHash+"-512.png")

		hasHashFile := fileExists(cacheHashFile)
		hasCache192 := fileExists(cache192)
		hasCache512 := fileExists(cache512)

		// Generate if forced or cache is not fully available.
		needsGeneration := shouldGeneratePWAIcons(shouldForce, hasHashFile, hasCache192, hasCache512)

		if needsGeneration {
			// Generate icons to memory once, then write to both sink and cache.
			icons, err := generators.GeneratePWAIconBytes(b.SourceFs, faviconPath)
			if err == nil {
				if wErr := generators.WritePWAIcons(b.Sink, filepath.Join(b.cfg.OutputDir, "static/images"), icons); wErr == nil {
					b.deps.Render.RegisterFile(filepath.Join(b.cfg.OutputDir, "static/images/icon-192.png"))
					b.deps.Render.RegisterFile(filepath.Join(b.cfg.OutputDir, "static/images/icon-512.png"))
				}

				_ = os.MkdirAll(cacheDir, 0755)
				// Save hash to cache
				_ = os.WriteFile(cacheHashFile, []byte(currentHash), 0644)

				// Persist generated bytes to cache for future reuse
				if data, ok := icons[192]; ok {
					_ = os.WriteFile(cache192, data, 0644)
				}
				if data, ok := icons[512]; ok {
					_ = os.WriteFile(cache512, data, 0644)
				}
			}
		} else {
			// Copy from cache to destination
			// Copy cached icons to VFS
			if data, err := os.ReadFile(cache192); err == nil {
				iconPath := filepath.Join(b.cfg.OutputDir, "static/images/icon-192.png")
				_ = b.Sink.WriteFile(iconPath, data)
				b.deps.Render.RegisterFile(iconPath)
			}
			if data, err := os.ReadFile(cache512); err == nil {
				iconPath := filepath.Join(b.cfg.OutputDir, "static/images/icon-512.png")
				_ = b.Sink.WriteFile(iconPath, data)
				b.deps.Render.RegisterFile(iconPath)
			}
		}
		return nil
	})

	return g.Wait()
}
