// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package models

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *CacheStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "TotalPosts":
			z.TotalPosts, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "TotalPosts")
				return
			}
		case "TotalSSR":
			z.TotalSSR, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "TotalSSR")
				return
			}
		case "StoreBytes":
			z.StoreBytes, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "StoreBytes")
				return
			}
		case "LastGC":
			z.LastGC, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "LastGC")
				return
			}
		case "BuildCount":
			z.BuildCount, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "BuildCount")
				return
			}
		case "SchemaVersion":
			z.SchemaVersion, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "SchemaVersion")
				return
			}
		case "InlinePosts":
			z.InlinePosts, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "InlinePosts")
				return
			}
		case "HashedPosts":
			z.HashedPosts, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "HashedPosts")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CacheStats) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 8
	// write "TotalPosts"
	err = en.Append(0x88, 0xaa, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.TotalPosts)
	if err != nil {
		err = msgp.WrapError(err, "TotalPosts")
		return
	}
	// write "TotalSSR"
	err = en.Append(0xa8, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x53, 0x52)
	if err != nil {
		return
	}
	err = en.WriteInt(z.TotalSSR)
	if err != nil {
		err = msgp.WrapError(err, "TotalSSR")
		return
	}
	// write "StoreBytes"
	err = en.Append(0xaa, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.StoreBytes)
	if err != nil {
		err = msgp.WrapError(err, "StoreBytes")
		return
	}
	// write "LastGC"
	err = en.Append(0xa6, 0x4c, 0x61, 0x73, 0x74, 0x47, 0x43)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.LastGC)
	if err != nil {
		err = msgp.WrapError(err, "LastGC")
		return
	}
	// write "BuildCount"
	err = en.Append(0xaa, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.BuildCount)
	if err != nil {
		err = msgp.WrapError(err, "BuildCount")
		return
	}
	// write "SchemaVersion"
	err = en.Append(0xad, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt(z.SchemaVersion)
	if err != nil {
		err = msgp.WrapError(err, "SchemaVersion")
		return
	}
	// write "InlinePosts"
	err = en.Append(0xab, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.InlinePosts)
	if err != nil {
		err = msgp.WrapError(err, "InlinePosts")
		return
	}
	// write "HashedPosts"
	err = en.Append(0xab, 0x48, 0x61, 0x73, 0x68, 0x65, 0x64, 0x50, 0x6f, 0x73, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.HashedPosts)
	if err != nil {
		err = msgp.WrapError(err, "HashedPosts")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CacheStats) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 8
	// string "TotalPosts"
	o = append(o, 0x88, 0xaa, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73)
	o = msgp.AppendInt(o, z.TotalPosts)
	// string "TotalSSR"
	o = append(o, 0xa8, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x53, 0x52)
	o = msgp.AppendInt(o, z.TotalSSR)
	// string "StoreBytes"
	o = append(o, 0xaa, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73)
	o = msgp.AppendInt64(o, z.StoreBytes)
	// string "LastGC"
	o = append(o, 0xa6, 0x4c, 0x61, 0x73, 0x74, 0x47, 0x43)
	o = msgp.AppendInt64(o, z.LastGC)
	// string "BuildCount"
	o = append(o, 0xaa, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendInt(o, z.BuildCount)
	// string "SchemaVersion"
	o = append(o, 0xad, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendInt(o, z.SchemaVersion)
	// string "InlinePosts"
	o = append(o, 0xab, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x73)
	o = msgp.AppendInt(o, z.InlinePosts)
	// string "HashedPosts"
	o = append(o, 0xab, 0x48, 0x61, 0x73, 0x68, 0x65, 0x64, 0x50, 0x6f, 0x73, 0x74, 0x73)
	o = msgp.AppendInt(o, z.HashedPosts)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CacheStats) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "TotalPosts":
			z.TotalPosts, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalPosts")
				return
			}
		case "TotalSSR":
			z.TotalSSR, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalSSR")
				return
			}
		case "StoreBytes":
			z.StoreBytes, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StoreBytes")
				return
			}
		case "LastGC":
			z.LastGC, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastGC")
				return
			}
		case "BuildCount":
			z.BuildCount, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BuildCount")
				return
			}
		case "SchemaVersion":
			z.SchemaVersion, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SchemaVersion")
				return
			}
		case "InlinePosts":
			z.InlinePosts, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "InlinePosts")
				return
			}
		case "HashedPosts":
			z.HashedPosts, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "HashedPosts")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CacheStats) Msgsize() (s int) {
	s = 1 + 11 + msgp.IntSize + 9 + msgp.IntSize + 11 + msgp.Int64Size + 7 + msgp.Int64Size + 11 + msgp.IntSize + 14 + msgp.IntSize + 12 + msgp.IntSize + 12 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompressionType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int
		zb0001, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CompressionType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z CompressionType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt(int(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z CompressionType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt(o, int(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompressionType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int
		zb0001, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CompressionType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CompressionType) Msgsize() (s int) {
	s = msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Dependencies) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Templates":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Templates")
				return
			}
			if cap(z.Templates) >= int(zb0002) {
				z.Templates = (z.Templates)[:zb0002]
			} else {
				z.Templates = make([]string, zb0002)
			}
			for za0001 := range z.Templates {
				z.Templates[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Templates", za0001)
					return
				}
			}
		case "Includes":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Includes")
				return
			}
			if cap(z.Includes) >= int(zb0003) {
				z.Includes = (z.Includes)[:zb0003]
			} else {
				z.Includes = make([]string, zb0003)
			}
			for za0002 := range z.Includes {
				z.Includes[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Includes", za0002)
					return
				}
			}
		case "Tags":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Tags")
				return
			}
			if cap(z.Tags) >= int(zb0004) {
				z.Tags = (z.Tags)[:zb0004]
			} else {
				z.Tags = make([]string, zb0004)
			}
			for za0003 := range z.Tags {
				z.Tags[za0003], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Tags", za0003)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Dependencies) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Templates"
	err = en.Append(0x83, 0xa9, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Templates)))
	if err != nil {
		err = msgp.WrapError(err, "Templates")
		return
	}
	for za0001 := range z.Templates {
		err = en.WriteString(z.Templates[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Templates", za0001)
			return
		}
	}
	// write "Includes"
	err = en.Append(0xa8, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Includes)))
	if err != nil {
		err = msgp.WrapError(err, "Includes")
		return
	}
	for za0002 := range z.Includes {
		err = en.WriteString(z.Includes[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Includes", za0002)
			return
		}
	}
	// write "Tags"
	err = en.Append(0xa4, 0x54, 0x61, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Tags)))
	if err != nil {
		err = msgp.WrapError(err, "Tags")
		return
	}
	for za0003 := range z.Tags {
		err = en.WriteString(z.Tags[za0003])
		if err != nil {
			err = msgp.WrapError(err, "Tags", za0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Dependencies) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Templates"
	o = append(o, 0x83, 0xa9, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Templates)))
	for za0001 := range z.Templates {
		o = msgp.AppendString(o, z.Templates[za0001])
	}
	// string "Includes"
	o = append(o, 0xa8, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Includes)))
	for za0002 := range z.Includes {
		o = msgp.AppendString(o, z.Includes[za0002])
	}
	// string "Tags"
	o = append(o, 0xa4, 0x54, 0x61, 0x67, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Tags)))
	for za0003 := range z.Tags {
		o = msgp.AppendString(o, z.Tags[za0003])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Dependencies) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Templates":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Templates")
				return
			}
			if cap(z.Templates) >= int(zb0002) {
				z.Templates = (z.Templates)[:zb0002]
			} else {
				z.Templates = make([]string, zb0002)
			}
			for za0001 := range z.Templates {
				z.Templates[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Templates", za0001)
					return
				}
			}
		case "Includes":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Includes")
				return
			}
			if cap(z.Includes) >= int(zb0003) {
				z.Includes = (z.Includes)[:zb0003]
			} else {
				z.Includes = make([]string, zb0003)
			}
			for za0002 := range z.Includes {
				z.Includes[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Includes", za0002)
					return
				}
			}
		case "Tags":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tags")
				return
			}
			if cap(z.Tags) >= int(zb0004) {
				z.Tags = (z.Tags)[:zb0004]
			} else {
				z.Tags = make([]string, zb0004)
			}
			for za0003 := range z.Tags {
				z.Tags[za0003], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Tags", za0003)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Dependencies) Msgsize() (s int) {
	s = 1 + 10 + msgp.ArrayHeaderSize
	for za0001 := range z.Templates {
		s += msgp.StringPrefixSize + len(z.Templates[za0001])
	}
	s += 9 + msgp.ArrayHeaderSize
	for za0002 := range z.Includes {
		s += msgp.StringPrefixSize + len(z.Includes[za0002])
	}
	s += 5 + msgp.ArrayHeaderSize
	for za0003 := range z.Tags {
		s += msgp.StringPrefixSize + len(z.Tags[za0003])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PostListMeta) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "Link":
			z.Link, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Link")
				return
			}
		case "Weight":
			z.Weight, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Weight")
				return
			}
		case "Version":
			z.Version, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "Date":
			z.Date, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Date")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PostListMeta) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "Title"
	err = en.Append(0x85, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Title)
	if err != nil {
		err = msgp.WrapError(err, "Title")
		return
	}
	// write "Link"
	err = en.Append(0xa4, 0x4c, 0x69, 0x6e, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteString(z.Link)
	if err != nil {
		err = msgp.WrapError(err, "Link")
		return
	}
	// write "Weight"
	err = en.Append(0xa6, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Weight)
	if err != nil {
		err = msgp.WrapError(err, "Weight")
		return
	}
	// write "Version"
	err = en.Append(0xa7, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Version)
	if err != nil {
		err = msgp.WrapError(err, "Version")
		return
	}
	// write "Date"
	err = en.Append(0xa4, 0x44, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Date)
	if err != nil {
		err = msgp.WrapError(err, "Date")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PostListMeta) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "Title"
	o = append(o, 0x85, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Title)
	// string "Link"
	o = append(o, 0xa4, 0x4c, 0x69, 0x6e, 0x6b)
	o = msgp.AppendString(o, z.Link)
	// string "Weight"
	o = append(o, 0xa6, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74)
	o = msgp.AppendInt(o, z.Weight)
	// string "Version"
	o = append(o, 0xa7, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Version)
	// string "Date"
	o = append(o, 0xa4, 0x44, 0x61, 0x74, 0x65)
	o = msgp.AppendTime(o, z.Date)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PostListMeta) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "Link":
			z.Link, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Link")
				return
			}
		case "Weight":
			z.Weight, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Weight")
				return
			}
		case "Version":
			z.Version, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "Date":
			z.Date, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Date")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PostListMeta) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Title) + 5 + msgp.StringPrefixSize + len(z.Link) + 7 + msgp.IntSize + 8 + msgp.StringPrefixSize + len(z.Version) + 5 + msgp.TimeSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PostMeta) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "PostID":
			z.PostID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PostID")
				return
			}
		case "Path":
			z.Path, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Path")
				return
			}
		case "ModTime":
			z.ModTime, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ModTime")
				return
			}
		case "ContentHash":
			z.ContentHash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ContentHash")
				return
			}
		case "BodyHash":
			z.BodyHash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "BodyHash")
				return
			}
		case "HTMLHash":
			z.HTMLHash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "HTMLHash")
				return
			}
		case "InlineHTML":
			z.InlineHTML, err = dc.ReadBytes(z.InlineHTML)
			if err != nil {
				err = msgp.WrapError(err, "InlineHTML")
				return
			}
		case "SSRInputHashes":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "SSRInputHashes")
				return
			}
			if cap(z.SSRInputHashes) >= int(zb0002) {
				z.SSRInputHashes = (z.SSRInputHashes)[:zb0002]
			} else {
				z.SSRInputHashes = make([]string, zb0002)
			}
			for za0001 := range z.SSRInputHashes {
				z.SSRInputHashes[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "SSRInputHashes", za0001)
					return
				}
			}
		case "Title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "Date":
			z.Date, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Date")
				return
			}
		case "Tags":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Tags")
				return
			}
			if cap(z.Tags) >= int(zb0003) {
				z.Tags = (z.Tags)[:zb0003]
			} else {
				z.Tags = make([]string, zb0003)
			}
			for za0002 := range z.Tags {
				z.Tags[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Tags", za0002)
					return
				}
			}
		case "WordCount":
			z.WordCount, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "WordCount")
				return
			}
		case "ReadingTime":
			z.ReadingTime, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "ReadingTime")
				return
			}
		case "Description":
			z.Description, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Description")
				return
			}
		case "Link":
			z.Link, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Link")
				return
			}
		case "Weight":
			z.Weight, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Weight")
				return
			}
		case "Pinned":
			z.Pinned, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Pinned")
				return
			}
		case "Draft":
			z.Draft, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Draft")
				return
			}
		case "Meta":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Meta")
				return
			}
			if z.Meta == nil {
				z.Meta = make(map[string]interface{}, zb0004)
			} else if len(z.Meta) > 0 {
				clear(z.Meta)
			}
			for zb0004 > 0 {
				zb0004--
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Meta")
					return
				}
				var za0004 interface{}
				za0004, err = dc.ReadIntf()
				if err != nil {
					err = msgp.WrapError(err, "Meta", za0003)
					return
				}
				z.Meta[za0003] = za0004
			}
		case "TOC":
			var zb0005 uint32
			zb0005, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "TOC")
				return
			}
			if cap(z.TOC) >= int(zb0005) {
				z.TOC = (z.TOC)[:zb0005]
			} else {
				z.TOC = make([]TOCEntry, zb0005)
			}
			for za0005 := range z.TOC {
				err = z.TOC[za0005].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "TOC", za0005)
					return
				}
			}
		case "Version":
			z.Version, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "CardHash":
			z.CardHash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "CardHash")
				return
			}
		case "HasImages":
			z.HasImages, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "HasImages")
				return
			}
		case "MathExpressions":
			var zb0006 uint32
			zb0006, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "MathExpressions")
				return
			}
			if cap(z.MathExpressions) >= int(zb0006) {
				z.MathExpressions = (z.MathExpressions)[:zb0006]
			} else {
				z.MathExpressions = make([]MathExpression, zb0006)
			}
			for za0006 := range z.MathExpressions {
				err = z.MathExpressions[za0006].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "MathExpressions", za0006)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PostMeta) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 24
	// write "PostID"
	err = en.Append(0xde, 0x0, 0x18, 0xa6, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.PostID)
	if err != nil {
		err = msgp.WrapError(err, "PostID")
		return
	}
	// write "Path"
	err = en.Append(0xa4, 0x50, 0x61, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Path)
	if err != nil {
		err = msgp.WrapError(err, "Path")
		return
	}
	// write "ModTime"
	err = en.Append(0xa7, 0x4d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.ModTime)
	if err != nil {
		err = msgp.WrapError(err, "ModTime")
		return
	}
	// write "ContentHash"
	err = en.Append(0xab, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.ContentHash)
	if err != nil {
		err = msgp.WrapError(err, "ContentHash")
		return
	}
	// write "BodyHash"
	err = en.Append(0xa8, 0x42, 0x6f, 0x64, 0x79, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.BodyHash)
	if err != nil {
		err = msgp.WrapError(err, "BodyHash")
		return
	}
	// write "HTMLHash"
	err = en.Append(0xa8, 0x48, 0x54, 0x4d, 0x4c, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.HTMLHash)
	if err != nil {
		err = msgp.WrapError(err, "HTMLHash")
		return
	}
	// write "InlineHTML"
	err = en.Append(0xaa, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x48, 0x54, 0x4d, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.InlineHTML)
	if err != nil {
		err = msgp.WrapError(err, "InlineHTML")
		return
	}
	// write "SSRInputHashes"
	err = en.Append(0xae, 0x53, 0x53, 0x52, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.SSRInputHashes)))
	if err != nil {
		err = msgp.WrapError(err, "SSRInputHashes")
		return
	}
	for za0001 := range z.SSRInputHashes {
		err = en.WriteString(z.SSRInputHashes[za0001])
		if err != nil {
			err = msgp.WrapError(err, "SSRInputHashes", za0001)
			return
		}
	}
	// write "Title"
	err = en.Append(0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Title)
	if err != nil {
		err = msgp.WrapError(err, "Title")
		return
	}
	// write "Date"
	err = en.Append(0xa4, 0x44, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Date)
	if err != nil {
		err = msgp.WrapError(err, "Date")
		return
	}
	// write "Tags"
	err = en.Append(0xa4, 0x54, 0x61, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Tags)))
	if err != nil {
		err = msgp.WrapError(err, "Tags")
		return
	}
	for za0002 := range z.Tags {
		err = en.WriteString(z.Tags[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Tags", za0002)
			return
		}
	}
	// write "WordCount"
	err = en.Append(0xa9, 0x57, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.WordCount)
	if err != nil {
		err = msgp.WrapError(err, "WordCount")
		return
	}
	// write "ReadingTime"
	err = en.Append(0xab, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.ReadingTime)
	if err != nil {
		err = msgp.WrapError(err, "ReadingTime")
		return
	}
	// write "Description"
	err = en.Append(0xab, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Description)
	if err != nil {
		err = msgp.WrapError(err, "Description")
		return
	}
	// write "Link"
	err = en.Append(0xa4, 0x4c, 0x69, 0x6e, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteString(z.Link)
	if err != nil {
		err = msgp.WrapError(err, "Link")
		return
	}
	// write "Weight"
	err = en.Append(0xa6, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Weight)
	if err != nil {
		err = msgp.WrapError(err, "Weight")
		return
	}
	// write "Pinned"
	err = en.Append(0xa6, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Pinned)
	if err != nil {
		err = msgp.WrapError(err, "Pinned")
		return
	}
	// write "Draft"
	err = en.Append(0xa5, 0x44, 0x72, 0x61, 0x66, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Draft)
	if err != nil {
		err = msgp.WrapError(err, "Draft")
		return
	}
	// write "Meta"
	err = en.Append(0xa4, 0x4d, 0x65, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Meta)))
	if err != nil {
		err = msgp.WrapError(err, "Meta")
		return
	}
	for za0003, za0004 := range z.Meta {
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "Meta")
			return
		}
		err = en.WriteIntf(za0004)
		if err != nil {
			err = msgp.WrapError(err, "Meta", za0003)
			return
		}
	}
	// write "TOC"
	err = en.Append(0xa3, 0x54, 0x4f, 0x43)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.TOC)))
	if err != nil {
		err = msgp.WrapError(err, "TOC")
		return
	}
	for za0005 := range z.TOC {
		err = z.TOC[za0005].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "TOC", za0005)
			return
		}
	}
	// write "Version"
	err = en.Append(0xa7, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Version)
	if err != nil {
		err = msgp.WrapError(err, "Version")
		return
	}
	// write "CardHash"
	err = en.Append(0xa8, 0x43, 0x61, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.CardHash)
	if err != nil {
		err = msgp.WrapError(err, "CardHash")
		return
	}
	// write "HasImages"
	err = en.Append(0xa9, 0x48, 0x61, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBool(z.HasImages)
	if err != nil {
		err = msgp.WrapError(err, "HasImages")
		return
	}
	// write "MathExpressions"
	err = en.Append(0xaf, 0x4d, 0x61, 0x74, 0x68, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.MathExpressions)))
	if err != nil {
		err = msgp.WrapError(err, "MathExpressions")
		return
	}
	for za0006 := range z.MathExpressions {
		err = z.MathExpressions[za0006].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "MathExpressions", za0006)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PostMeta) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 24
	// string "PostID"
	o = append(o, 0xde, 0x0, 0x18, 0xa6, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x44)
	o = msgp.AppendString(o, z.PostID)
	// string "Path"
	o = append(o, 0xa4, 0x50, 0x61, 0x74, 0x68)
	o = msgp.AppendString(o, z.Path)
	// string "ModTime"
	o = append(o, 0xa7, 0x4d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65)
	o = msgp.AppendInt64(o, z.ModTime)
	// string "ContentHash"
	o = append(o, 0xab, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.ContentHash)
	// string "BodyHash"
	o = append(o, 0xa8, 0x42, 0x6f, 0x64, 0x79, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.BodyHash)
	// string "HTMLHash"
	o = append(o, 0xa8, 0x48, 0x54, 0x4d, 0x4c, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.HTMLHash)
	// string "InlineHTML"
	o = append(o, 0xaa, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x48, 0x54, 0x4d, 0x4c)
	o = msgp.AppendBytes(o, z.InlineHTML)
	// string "SSRInputHashes"
	o = append(o, 0xae, 0x53, 0x53, 0x52, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.SSRInputHashes)))
	for za0001 := range z.SSRInputHashes {
		o = msgp.AppendString(o, z.SSRInputHashes[za0001])
	}
	// string "Title"
	o = append(o, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Title)
	// string "Date"
	o = append(o, 0xa4, 0x44, 0x61, 0x74, 0x65)
	o = msgp.AppendTime(o, z.Date)
	// string "Tags"
	o = append(o, 0xa4, 0x54, 0x61, 0x67, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Tags)))
	for za0002 := range z.Tags {
		o = msgp.AppendString(o, z.Tags[za0002])
	}
	// string "WordCount"
	o = append(o, 0xa9, 0x57, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendInt(o, z.WordCount)
	// string "ReadingTime"
	o = append(o, 0xab, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65)
	o = msgp.AppendInt(o, z.ReadingTime)
	// string "Description"
	o = append(o, 0xab, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Description)
	// string "Link"
	o = append(o, 0xa4, 0x4c, 0x69, 0x6e, 0x6b)
	o = msgp.AppendString(o, z.Link)
	// string "Weight"
	o = append(o, 0xa6, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74)
	o = msgp.AppendInt(o, z.Weight)
	// string "Pinned"
	o = append(o, 0xa6, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64)
	o = msgp.AppendBool(o, z.Pinned)
	// string "Draft"
	o = append(o, 0xa5, 0x44, 0x72, 0x61, 0x66, 0x74)
	o = msgp.AppendBool(o, z.Draft)
	// string "Meta"
	o = append(o, 0xa4, 0x4d, 0x65, 0x74, 0x61)
	o = msgp.AppendMapHeader(o, uint32(len(z.Meta)))
	for za0003, za0004 := range z.Meta {
		o = msgp.AppendString(o, za0003)
		o, err = msgp.AppendIntf(o, za0004)
		if err != nil {
			err = msgp.WrapError(err, "Meta", za0003)
			return
		}
	}
	// string "TOC"
	o = append(o, 0xa3, 0x54, 0x4f, 0x43)
	o = msgp.AppendArrayHeader(o, uint32(len(z.TOC)))
	for za0005 := range z.TOC {
		o, err = z.TOC[za0005].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "TOC", za0005)
			return
		}
	}
	// string "Version"
	o = append(o, 0xa7, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Version)
	// string "CardHash"
	o = append(o, 0xa8, 0x43, 0x61, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.CardHash)
	// string "HasImages"
	o = append(o, 0xa9, 0x48, 0x61, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73)
	o = msgp.AppendBool(o, z.HasImages)
	// string "MathExpressions"
	o = append(o, 0xaf, 0x4d, 0x61, 0x74, 0x68, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.MathExpressions)))
	for za0006 := range z.MathExpressions {
		o, err = z.MathExpressions[za0006].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "MathExpressions", za0006)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PostMeta) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "PostID":
			z.PostID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PostID")
				return
			}
		case "Path":
			z.Path, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Path")
				return
			}
		case "ModTime":
			z.ModTime, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ModTime")
				return
			}
		case "ContentHash":
			z.ContentHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ContentHash")
				return
			}
		case "BodyHash":
			z.BodyHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BodyHash")
				return
			}
		case "HTMLHash":
			z.HTMLHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "HTMLHash")
				return
			}
		case "InlineHTML":
			z.InlineHTML, bts, err = msgp.ReadBytesBytes(bts, z.InlineHTML)
			if err != nil {
				err = msgp.WrapError(err, "InlineHTML")
				return
			}
		case "SSRInputHashes":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SSRInputHashes")
				return
			}
			if cap(z.SSRInputHashes) >= int(zb0002) {
				z.SSRInputHashes = (z.SSRInputHashes)[:zb0002]
			} else {
				z.SSRInputHashes = make([]string, zb0002)
			}
			for za0001 := range z.SSRInputHashes {
				z.SSRInputHashes[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "SSRInputHashes", za0001)
					return
				}
			}
		case "Title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "Date":
			z.Date, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Date")
				return
			}
		case "Tags":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tags")
				return
			}
			if cap(z.Tags) >= int(zb0003) {
				z.Tags = (z.Tags)[:zb0003]
			} else {
				z.Tags = make([]string, zb0003)
			}
			for za0002 := range z.Tags {
				z.Tags[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Tags", za0002)
					return
				}
			}
		case "WordCount":
			z.WordCount, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WordCount")
				return
			}
		case "ReadingTime":
			z.ReadingTime, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ReadingTime")
				return
			}
		case "Description":
			z.Description, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Description")
				return
			}
		case "Link":
			z.Link, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Link")
				return
			}
		case "Weight":
			z.Weight, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Weight")
				return
			}
		case "Pinned":
			z.Pinned, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Pinned")
				return
			}
		case "Draft":
			z.Draft, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Draft")
				return
			}
		case "Meta":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Meta")
				return
			}
			if z.Meta == nil {
				z.Meta = make(map[string]interface{}, zb0004)
			} else if len(z.Meta) > 0 {
				clear(z.Meta)
			}
			for zb0004 > 0 {
				var za0004 interface{}
				zb0004--
				var za0003 string
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Meta")
					return
				}
				za0004, bts, err = msgp.ReadIntfBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Meta", za0003)
					return
				}
				z.Meta[za0003] = za0004
			}
		case "TOC":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TOC")
				return
			}
			if cap(z.TOC) >= int(zb0005) {
				z.TOC = (z.TOC)[:zb0005]
			} else {
				z.TOC = make([]TOCEntry, zb0005)
			}
			for za0005 := range z.TOC {
				bts, err = z.TOC[za0005].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "TOC", za0005)
					return
				}
			}
		case "Version":
			z.Version, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "CardHash":
			z.CardHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CardHash")
				return
			}
		case "HasImages":
			z.HasImages, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "HasImages")
				return
			}
		case "MathExpressions":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MathExpressions")
				return
			}
			if cap(z.MathExpressions) >= int(zb0006) {
				z.MathExpressions = (z.MathExpressions)[:zb0006]
			} else {
				z.MathExpressions = make([]MathExpression, zb0006)
			}
			for za0006 := range z.MathExpressions {
				bts, err = z.MathExpressions[za0006].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "MathExpressions", za0006)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PostMeta) Msgsize() (s int) {
	s = 3 + 7 + msgp.StringPrefixSize + len(z.PostID) + 5 + msgp.StringPrefixSize + len(z.Path) + 8 + msgp.Int64Size + 12 + msgp.StringPrefixSize + len(z.ContentHash) + 9 + msgp.StringPrefixSize + len(z.BodyHash) + 9 + msgp.StringPrefixSize + len(z.HTMLHash) + 11 + msgp.BytesPrefixSize + len(z.InlineHTML) + 15 + msgp.ArrayHeaderSize
	for za0001 := range z.SSRInputHashes {
		s += msgp.StringPrefixSize + len(z.SSRInputHashes[za0001])
	}
	s += 6 + msgp.StringPrefixSize + len(z.Title) + 5 + msgp.TimeSize + 5 + msgp.ArrayHeaderSize
	for za0002 := range z.Tags {
		s += msgp.StringPrefixSize + len(z.Tags[za0002])
	}
	s += 10 + msgp.IntSize + 12 + msgp.IntSize + 12 + msgp.StringPrefixSize + len(z.Description) + 5 + msgp.StringPrefixSize + len(z.Link) + 7 + msgp.IntSize + 7 + msgp.BoolSize + 6 + msgp.BoolSize + 5 + msgp.MapHeaderSize
	if z.Meta != nil {
		for za0003, za0004 := range z.Meta {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.GuessSize(za0004)
		}
	}
	s += 4 + msgp.ArrayHeaderSize
	for za0005 := range z.TOC {
		s += z.TOC[za0005].Msgsize()
	}
	s += 8 + msgp.StringPrefixSize + len(z.Version) + 9 + msgp.StringPrefixSize + len(z.CardHash) + 10 + msgp.BoolSize + 16 + msgp.ArrayHeaderSize
	for za0006 := range z.MathExpressions {
		s += z.MathExpressions[za0006].Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SSRArtifact) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			z.Type, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "InputHash":
			z.InputHash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "InputHash")
				return
			}
		case "OutputHash":
			z.OutputHash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "OutputHash")
				return
			}
		case "RefCount":
			z.RefCount, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "RefCount")
				return
			}
		case "Size":
			z.Size, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Size")
				return
			}
		case "CreatedAt":
			z.CreatedAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "CreatedAt")
				return
			}
		case "Compressed":
			z.Compressed, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Compressed")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SSRArtifact) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "Type"
	err = en.Append(0x87, 0xa4, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Type)
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "InputHash"
	err = en.Append(0xa9, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.InputHash)
	if err != nil {
		err = msgp.WrapError(err, "InputHash")
		return
	}
	// write "OutputHash"
	err = en.Append(0xaa, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.OutputHash)
	if err != nil {
		err = msgp.WrapError(err, "OutputHash")
		return
	}
	// write "RefCount"
	err = en.Append(0xa8, 0x52, 0x65, 0x66, 0x43, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.RefCount)
	if err != nil {
		err = msgp.WrapError(err, "RefCount")
		return
	}
	// write "Size"
	err = en.Append(0xa4, 0x53, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Size)
	if err != nil {
		err = msgp.WrapError(err, "Size")
		return
	}
	// write "CreatedAt"
	err = en.Append(0xa9, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.CreatedAt)
	if err != nil {
		err = msgp.WrapError(err, "CreatedAt")
		return
	}
	// write "Compressed"
	err = en.Append(0xaa, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Compressed)
	if err != nil {
		err = msgp.WrapError(err, "Compressed")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SSRArtifact) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "Type"
	o = append(o, 0x87, 0xa4, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendString(o, z.Type)
	// string "InputHash"
	o = append(o, 0xa9, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.InputHash)
	// string "OutputHash"
	o = append(o, 0xaa, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.OutputHash)
	// string "RefCount"
	o = append(o, 0xa8, 0x52, 0x65, 0x66, 0x43, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendInt(o, z.RefCount)
	// string "Size"
	o = append(o, 0xa4, 0x53, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt64(o, z.Size)
	// string "CreatedAt"
	o = append(o, 0xa9, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74)
	o = msgp.AppendInt64(o, z.CreatedAt)
	// string "Compressed"
	o = append(o, 0xaa, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64)
	o = msgp.AppendBool(o, z.Compressed)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SSRArtifact) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			z.Type, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "InputHash":
			z.InputHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "InputHash")
				return
			}
		case "OutputHash":
			z.OutputHash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "OutputHash")
				return
			}
		case "RefCount":
			z.RefCount, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RefCount")
				return
			}
		case "Size":
			z.Size, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Size")
				return
			}
		case "CreatedAt":
			z.CreatedAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreatedAt")
				return
			}
		case "Compressed":
			z.Compressed, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Compressed")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SSRArtifact) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Type) + 10 + msgp.StringPrefixSize + len(z.InputHash) + 11 + msgp.StringPrefixSize + len(z.OutputHash) + 9 + msgp.IntSize + 5 + msgp.Int64Size + 10 + msgp.Int64Size + 11 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SearchRecord) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "NormalizedTitle":
			z.NormalizedTitle, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "NormalizedTitle")
				return
			}
		case "BM25Data":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "BM25Data")
				return
			}
			if z.BM25Data == nil {
				z.BM25Data = make(map[string]int, zb0002)
			} else if len(z.BM25Data) > 0 {
				clear(z.BM25Data)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "BM25Data")
					return
				}
				var za0002 int
				za0002, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "BM25Data", za0001)
					return
				}
				z.BM25Data[za0001] = za0002
			}
		case "DocLen":
			z.DocLen, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "DocLen")
				return
			}
		case "Content":
			z.Content, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "NormalizedTags":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "NormalizedTags")
				return
			}
			if cap(z.NormalizedTags) >= int(zb0003) {
				z.NormalizedTags = (z.NormalizedTags)[:zb0003]
			} else {
				z.NormalizedTags = make([]string, zb0003)
			}
			for za0003 := range z.NormalizedTags {
				z.NormalizedTags[za0003], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "NormalizedTags", za0003)
					return
				}
			}
		case "StemMap":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "StemMap")
				return
			}
			if z.StemMap == nil {
				z.StemMap = make(map[string]string, zb0004)
			} else if len(z.StemMap) > 0 {
				clear(z.StemMap)
			}
			for zb0004 > 0 {
				zb0004--
				var za0004 string
				za0004, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "StemMap")
					return
				}
				var za0005 string
				za0005, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "StemMap", za0004)
					return
				}
				z.StemMap[za0004] = za0005
			}
		case "PositionalIndex":
			var zb0005 uint32
			zb0005, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "PositionalIndex")
				return
			}
			if z.PositionalIndex == nil {
				z.PositionalIndex = make(map[string][]int, zb0005)
			} else if len(z.PositionalIndex) > 0 {
				clear(z.PositionalIndex)
			}
			for zb0005 > 0 {
				zb0005--
				var za0006 string
				za0006, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex")
					return
				}
				var za0007 []int
				var zb0006 uint32
				zb0006, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex", za0006)
					return
				}
				if cap(za0007) >= int(zb0006) {
					za0007 = (za0007)[:zb0006]
				} else {
					za0007 = make([]int, zb0006)
				}
				for za0008 := range za0007 {
					za0007[za0008], err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "PositionalIndex", za0006, za0008)
						return
					}
				}
				z.PositionalIndex[za0006] = za0007
			}
		case "ByteOffsets":
			var zb0007 uint32
			zb0007, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "ByteOffsets")
				return
			}
			if z.ByteOffsets == nil {
				z.ByteOffsets = make(map[string][]int, zb0007)
			} else if len(z.ByteOffsets) > 0 {
				clear(z.ByteOffsets)
			}
			for zb0007 > 0 {
				zb0007--
				var za0009 string
				za0009, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "ByteOffsets")
					return
				}
				var za0010 []int
				var zb0008 uint32
				zb0008, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "ByteOffsets", za0009)
					return
				}
				if cap(za0010) >= int(zb0008) {
					za0010 = (za0010)[:zb0008]
				} else {
					za0010 = make([]int, zb0008)
				}
				for za0011 := range za0010 {
					za0010[za0011], err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "ByteOffsets", za0009, za0011)
						return
					}
				}
				z.ByteOffsets[za0009] = za0010
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SearchRecord) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 9
	// write "Title"
	err = en.Append(0x89, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Title)
	if err != nil {
		err = msgp.WrapError(err, "Title")
		return
	}
	// write "NormalizedTitle"
	err = en.Append(0xaf, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.NormalizedTitle)
	if err != nil {
		err = msgp.WrapError(err, "NormalizedTitle")
		return
	}
	// write "BM25Data"
	err = en.Append(0xa8, 0x42, 0x4d, 0x32, 0x35, 0x44, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.BM25Data)))
	if err != nil {
		err = msgp.WrapError(err, "BM25Data")
		return
	}
	for za0001, za0002 := range z.BM25Data {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "BM25Data")
			return
		}
		err = en.WriteInt(za0002)
		if err != nil {
			err = msgp.WrapError(err, "BM25Data", za0001)
			return
		}
	}
	// write "DocLen"
	err = en.Append(0xa6, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt(z.DocLen)
	if err != nil {
		err = msgp.WrapError(err, "DocLen")
		return
	}
	// write "Content"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Content)
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	// write "NormalizedTags"
	err = en.Append(0xae, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x61, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.NormalizedTags)))
	if err != nil {
		err = msgp.WrapError(err, "NormalizedTags")
		return
	}
	for za0003 := range z.NormalizedTags {
		err = en.WriteString(z.NormalizedTags[za0003])
		if err != nil {
			err = msgp.WrapError(err, "NormalizedTags", za0003)
			return
		}
	}
	// write "StemMap"
	err = en.Append(0xa7, 0x53, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.StemMap)))
	if err != nil {
		err = msgp.WrapError(err, "StemMap")
		return
	}
	for za0004, za0005 := range z.StemMap {
		err = en.WriteString(za0004)
		if err != nil {
			err = msgp.WrapError(err, "StemMap")
			return
		}
		err = en.WriteString(za0005)
		if err != nil {
			err = msgp.WrapError(err, "StemMap", za0004)
			return
		}
	}
	// write "PositionalIndex"
	err = en.Append(0xaf, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.PositionalIndex)))
	if err != nil {
		err = msgp.WrapError(err, "PositionalIndex")
		return
	}
	for za0006, za0007 := range z.PositionalIndex {
		err = en.WriteString(za0006)
		if err != nil {
			err = msgp.WrapError(err, "PositionalIndex")
			return
		}
		err = en.WriteArrayHeader(uint32(len(za0007)))
		if err != nil {
			err = msgp.WrapError(err, "PositionalIndex", za0006)
			return
		}
		for za0008 := range za0007 {
			err = en.WriteInt(za0007[za0008])
			if err != nil {
				err = msgp.WrapError(err, "PositionalIndex", za0006, za0008)
				return
			}
		}
	}
	// write "ByteOffsets"
	err = en.Append(0xab, 0x42, 0x79, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.ByteOffsets)))
	if err != nil {
		err = msgp.WrapError(err, "ByteOffsets")
		return
	}
	for za0009, za0010 := range z.ByteOffsets {
		err = en.WriteString(za0009)
		if err != nil {
			err = msgp.WrapError(err, "ByteOffsets")
			return
		}
		err = en.WriteArrayHeader(uint32(len(za0010)))
		if err != nil {
			err = msgp.WrapError(err, "ByteOffsets", za0009)
			return
		}
		for za0011 := range za0010 {
			err = en.WriteInt(za0010[za0011])
			if err != nil {
				err = msgp.WrapError(err, "ByteOffsets", za0009, za0011)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SearchRecord) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 9
	// string "Title"
	o = append(o, 0x89, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Title)
	// string "NormalizedTitle"
	o = append(o, 0xaf, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.NormalizedTitle)
	// string "BM25Data"
	o = append(o, 0xa8, 0x42, 0x4d, 0x32, 0x35, 0x44, 0x61, 0x74, 0x61)
	o = msgp.AppendMapHeader(o, uint32(len(z.BM25Data)))
	for za0001, za0002 := range z.BM25Data {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendInt(o, za0002)
	}
	// string "DocLen"
	o = append(o, 0xa6, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e)
	o = msgp.AppendInt(o, z.DocLen)
	// string "Content"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	o = msgp.AppendString(o, z.Content)
	// string "NormalizedTags"
	o = append(o, 0xae, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x61, 0x67, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.NormalizedTags)))
	for za0003 := range z.NormalizedTags {
		o = msgp.AppendString(o, z.NormalizedTags[za0003])
	}
	// string "StemMap"
	o = append(o, 0xa7, 0x53, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x70)
	o = msgp.AppendMapHeader(o, uint32(len(z.StemMap)))
	for za0004, za0005 := range z.StemMap {
		o = msgp.AppendString(o, za0004)
		o = msgp.AppendString(o, za0005)
	}
	// string "PositionalIndex"
	o = append(o, 0xaf, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78)
	o = msgp.AppendMapHeader(o, uint32(len(z.PositionalIndex)))
	for za0006, za0007 := range z.PositionalIndex {
		o = msgp.AppendString(o, za0006)
		o = msgp.AppendArrayHeader(o, uint32(len(za0007)))
		for za0008 := range za0007 {
			o = msgp.AppendInt(o, za0007[za0008])
		}
	}
	// string "ByteOffsets"
	o = append(o, 0xab, 0x42, 0x79, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.ByteOffsets)))
	for za0009, za0010 := range z.ByteOffsets {
		o = msgp.AppendString(o, za0009)
		o = msgp.AppendArrayHeader(o, uint32(len(za0010)))
		for za0011 := range za0010 {
			o = msgp.AppendInt(o, za0010[za0011])
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SearchRecord) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "NormalizedTitle":
			z.NormalizedTitle, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NormalizedTitle")
				return
			}
		case "BM25Data":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BM25Data")
				return
			}
			if z.BM25Data == nil {
				z.BM25Data = make(map[string]int, zb0002)
			} else if len(z.BM25Data) > 0 {
				clear(z.BM25Data)
			}
			for zb0002 > 0 {
				var za0002 int
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "BM25Data")
					return
				}
				za0002, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "BM25Data", za0001)
					return
				}
				z.BM25Data[za0001] = za0002
			}
		case "DocLen":
			z.DocLen, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DocLen")
				return
			}
		case "Content":
			z.Content, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "NormalizedTags":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NormalizedTags")
				return
			}
			if cap(z.NormalizedTags) >= int(zb0003) {
				z.NormalizedTags = (z.NormalizedTags)[:zb0003]
			} else {
				z.NormalizedTags = make([]string, zb0003)
			}
			for za0003 := range z.NormalizedTags {
				z.NormalizedTags[za0003], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "NormalizedTags", za0003)
					return
				}
			}
		case "StemMap":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StemMap")
				return
			}
			if z.StemMap == nil {
				z.StemMap = make(map[string]string, zb0004)
			} else if len(z.StemMap) > 0 {
				clear(z.StemMap)
			}
			for zb0004 > 0 {
				var za0005 string
				zb0004--
				var za0004 string
				za0004, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StemMap")
					return
				}
				za0005, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StemMap", za0004)
					return
				}
				z.StemMap[za0004] = za0005
			}
		case "PositionalIndex":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PositionalIndex")
				return
			}
			if z.PositionalIndex == nil {
				z.PositionalIndex = make(map[string][]int, zb0005)
			} else if len(z.PositionalIndex) > 0 {
				clear(z.PositionalIndex)
			}
			for zb0005 > 0 {
				var za0007 []int
				zb0005--
				var za0006 string
				za0006, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex")
					return
				}
				var zb0006 uint32
				zb0006, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex", za0006)
					return
				}
				if cap(za0007) >= int(zb0006) {
					za0007 = (za0007)[:zb0006]
				} else {
					za0007 = make([]int, zb0006)
				}
				for za0008 := range za0007 {
					za0007[za0008], bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "PositionalIndex", za0006, za0008)
						return
					}
				}
				z.PositionalIndex[za0006] = za0007
			}
		case "ByteOffsets":
			var zb0007 uint32
			zb0007, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ByteOffsets")
				return
			}
			if z.ByteOffsets == nil {
				z.ByteOffsets = make(map[string][]int, zb0007)
			} else if len(z.ByteOffsets) > 0 {
				clear(z.ByteOffsets)
			}
			for zb0007 > 0 {
				var za0010 []int
				zb0007--
				var za0009 string
				za0009, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ByteOffsets")
					return
				}
				var zb0008 uint32
				zb0008, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ByteOffsets", za0009)
					return
				}
				if cap(za0010) >= int(zb0008) {
					za0010 = (za0010)[:zb0008]
				} else {
					za0010 = make([]int, zb0008)
				}
				for za0011 := range za0010 {
					za0010[za0011], bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "ByteOffsets", za0009, za0011)
						return
					}
				}
				z.ByteOffsets[za0009] = za0010
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SearchRecord) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Title) + 16 + msgp.StringPrefixSize + len(z.NormalizedTitle) + 9 + msgp.MapHeaderSize
	if z.BM25Data != nil {
		for za0001, za0002 := range z.BM25Data {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.IntSize
		}
	}
	s += 7 + msgp.IntSize + 8 + msgp.StringPrefixSize + len(z.Content) + 15 + msgp.ArrayHeaderSize
	for za0003 := range z.NormalizedTags {
		s += msgp.StringPrefixSize + len(z.NormalizedTags[za0003])
	}
	s += 8 + msgp.MapHeaderSize
	if z.StemMap != nil {
		for za0004, za0005 := range z.StemMap {
			_ = za0005
			s += msgp.StringPrefixSize + len(za0004) + msgp.StringPrefixSize + len(za0005)
		}
	}
	s += 16 + msgp.MapHeaderSize
	if z.PositionalIndex != nil {
		for za0006, za0007 := range z.PositionalIndex {
			_ = za0007
			s += msgp.StringPrefixSize + len(za0006) + msgp.ArrayHeaderSize + (len(za0007) * (msgp.IntSize))
		}
	}
	s += 12 + msgp.MapHeaderSize
	if z.ByteOffsets != nil {
		for za0009, za0010 := range z.ByteOffsets {
			_ = za0010
			s += msgp.StringPrefixSize + len(za0009) + msgp.ArrayHeaderSize + (len(za0010) * (msgp.IntSize))
		}
	}
	return
}
