// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package models

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *AuthorConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "URL":
			z.URL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z AuthorConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Name"
	err = en.Append(0x82, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "URL"
	err = en.Append(0xa3, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.URL)
	if err != nil {
		err = msgp.WrapError(err, "URL")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z AuthorConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Name"
	o = append(o, 0x82, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "URL"
	o = append(o, 0xa3, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.URL)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *AuthorConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "URL":
			z.URL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z AuthorConfig) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 4 + msgp.StringPrefixSize + len(z.URL)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *FeaturesConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "UseRawMarkdown":
			z.UseRawMarkdown, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "UseRawMarkdown")
				return
			}
		case "Generators":
			err = z.Generators.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Generators")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *FeaturesConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "UseRawMarkdown"
	err = en.Append(0x82, 0xae, 0x55, 0x73, 0x65, 0x52, 0x61, 0x77, 0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteBool(z.UseRawMarkdown)
	if err != nil {
		err = msgp.WrapError(err, "UseRawMarkdown")
		return
	}
	// write "Generators"
	err = en.Append(0xaa, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73)
	if err != nil {
		return
	}
	err = z.Generators.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Generators")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *FeaturesConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "UseRawMarkdown"
	o = append(o, 0x82, 0xae, 0x55, 0x73, 0x65, 0x52, 0x61, 0x77, 0x4d, 0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e)
	o = msgp.AppendBool(o, z.UseRawMarkdown)
	// string "Generators"
	o = append(o, 0xaa, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73)
	o, err = z.Generators.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Generators")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *FeaturesConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "UseRawMarkdown":
			z.UseRawMarkdown, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UseRawMarkdown")
				return
			}
		case "Generators":
			bts, err = z.Generators.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Generators")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *FeaturesConfig) Msgsize() (s int) {
	s = 1 + 15 + msgp.BoolSize + 11 + z.Generators.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *GeneratorsConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "IsSitemapEnabled":
			z.IsSitemapEnabled, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "IsSitemapEnabled")
				return
			}
		case "IsRSSEnabled":
			z.IsRSSEnabled, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "IsRSSEnabled")
				return
			}
		case "Graph":
			err = z.Graph.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Graph")
				return
			}
		case "IsPWAEnabled":
			z.IsPWAEnabled, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "IsPWAEnabled")
				return
			}
		case "Search":
			err = z.Search.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Search")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GeneratorsConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "IsSitemapEnabled"
	err = en.Append(0x85, 0xb0, 0x49, 0x73, 0x53, 0x69, 0x74, 0x65, 0x6d, 0x61, 0x70, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteBool(z.IsSitemapEnabled)
	if err != nil {
		err = msgp.WrapError(err, "IsSitemapEnabled")
		return
	}
	// write "IsRSSEnabled"
	err = en.Append(0xac, 0x49, 0x73, 0x52, 0x53, 0x53, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteBool(z.IsRSSEnabled)
	if err != nil {
		err = msgp.WrapError(err, "IsRSSEnabled")
		return
	}
	// write "Graph"
	err = en.Append(0xa5, 0x47, 0x72, 0x61, 0x70, 0x68)
	if err != nil {
		return
	}
	err = z.Graph.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Graph")
		return
	}
	// write "IsPWAEnabled"
	err = en.Append(0xac, 0x49, 0x73, 0x50, 0x57, 0x41, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteBool(z.IsPWAEnabled)
	if err != nil {
		err = msgp.WrapError(err, "IsPWAEnabled")
		return
	}
	// write "Search"
	err = en.Append(0xa6, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68)
	if err != nil {
		return
	}
	err = z.Search.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Search")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GeneratorsConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "IsSitemapEnabled"
	o = append(o, 0x85, 0xb0, 0x49, 0x73, 0x53, 0x69, 0x74, 0x65, 0x6d, 0x61, 0x70, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	o = msgp.AppendBool(o, z.IsSitemapEnabled)
	// string "IsRSSEnabled"
	o = append(o, 0xac, 0x49, 0x73, 0x52, 0x53, 0x53, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	o = msgp.AppendBool(o, z.IsRSSEnabled)
	// string "Graph"
	o = append(o, 0xa5, 0x47, 0x72, 0x61, 0x70, 0x68)
	o, err = z.Graph.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Graph")
		return
	}
	// string "IsPWAEnabled"
	o = append(o, 0xac, 0x49, 0x73, 0x50, 0x57, 0x41, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	o = msgp.AppendBool(o, z.IsPWAEnabled)
	// string "Search"
	o = append(o, 0xa6, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68)
	o, err = z.Search.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Search")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GeneratorsConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "IsSitemapEnabled":
			z.IsSitemapEnabled, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsSitemapEnabled")
				return
			}
		case "IsRSSEnabled":
			z.IsRSSEnabled, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsRSSEnabled")
				return
			}
		case "Graph":
			bts, err = z.Graph.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Graph")
				return
			}
		case "IsPWAEnabled":
			z.IsPWAEnabled, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsPWAEnabled")
				return
			}
		case "Search":
			bts, err = z.Search.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Search")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GeneratorsConfig) Msgsize() (s int) {
	s = 1 + 17 + msgp.BoolSize + 13 + msgp.BoolSize + 6 + z.Graph.Msgsize() + 13 + msgp.BoolSize + 7 + z.Search.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MenuEntry) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "URL":
			z.URL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "Target":
			z.Target, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Target")
				return
			}
		case "ID":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Class":
			z.Class, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Class")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MenuEntry) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "Name"
	err = en.Append(0x85, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "URL"
	err = en.Append(0xa3, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.URL)
	if err != nil {
		err = msgp.WrapError(err, "URL")
		return
	}
	// write "Target"
	err = en.Append(0xa6, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Target)
	if err != nil {
		err = msgp.WrapError(err, "Target")
		return
	}
	// write "ID"
	err = en.Append(0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "Class"
	err = en.Append(0xa5, 0x43, 0x6c, 0x61, 0x73, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.Class)
	if err != nil {
		err = msgp.WrapError(err, "Class")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MenuEntry) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "Name"
	o = append(o, 0x85, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "URL"
	o = append(o, 0xa3, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.URL)
	// string "Target"
	o = append(o, 0xa6, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74)
	o = msgp.AppendString(o, z.Target)
	// string "ID"
	o = append(o, 0xa2, 0x49, 0x44)
	o = msgp.AppendString(o, z.ID)
	// string "Class"
	o = append(o, 0xa5, 0x43, 0x6c, 0x61, 0x73, 0x73)
	o = msgp.AppendString(o, z.Class)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MenuEntry) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "URL":
			z.URL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "Target":
			z.Target, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Target")
				return
			}
		case "ID":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Class":
			z.Class, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Class")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MenuEntry) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 4 + msgp.StringPrefixSize + len(z.URL) + 7 + msgp.StringPrefixSize + len(z.Target) + 3 + msgp.StringPrefixSize + len(z.ID) + 6 + msgp.StringPrefixSize + len(z.Class)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NavbarContextConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "BtnLabel":
			z.BtnLabel, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "BtnLabel")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NavbarContextConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Title"
	err = en.Append(0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Title)
	if err != nil {
		err = msgp.WrapError(err, "Title")
		return
	}
	// write "BtnLabel"
	err = en.Append(0xa8, 0x42, 0x74, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.BtnLabel)
	if err != nil {
		err = msgp.WrapError(err, "BtnLabel")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NavbarContextConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Title"
	o = append(o, 0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Title)
	// string "BtnLabel"
	o = append(o, 0xa8, 0x42, 0x74, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c)
	o = msgp.AppendString(o, z.BtnLabel)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NavbarContextConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "BtnLabel":
			z.BtnLabel, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BtnLabel")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NavbarContextConfig) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Title) + 9 + msgp.StringPrefixSize + len(z.BtnLabel)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NavbarIdentityConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Home":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Home")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Home")
					return
				}
				switch msgp.UnsafeString(field) {
				case "Title":
					z.Home.Title, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Home", "Title")
						return
					}
				case "BtnLabel":
					z.Home.BtnLabel, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Home", "BtnLabel")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Home")
						return
					}
				}
			}
		case "Section":
			var zb0003 uint32
			zb0003, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Section")
				return
			}
			for zb0003 > 0 {
				zb0003--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Section")
					return
				}
				switch msgp.UnsafeString(field) {
				case "Title":
					z.Section.Title, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Section", "Title")
						return
					}
				case "BtnLabel":
					z.Section.BtnLabel, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Section", "BtnLabel")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Section")
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NavbarIdentityConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Home"
	err = en.Append(0x82, 0xa4, 0x48, 0x6f, 0x6d, 0x65)
	if err != nil {
		return
	}
	// map header, size 2
	// write "Title"
	err = en.Append(0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Home.Title)
	if err != nil {
		err = msgp.WrapError(err, "Home", "Title")
		return
	}
	// write "BtnLabel"
	err = en.Append(0xa8, 0x42, 0x74, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Home.BtnLabel)
	if err != nil {
		err = msgp.WrapError(err, "Home", "BtnLabel")
		return
	}
	// write "Section"
	err = en.Append(0xa7, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	// map header, size 2
	// write "Title"
	err = en.Append(0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Section.Title)
	if err != nil {
		err = msgp.WrapError(err, "Section", "Title")
		return
	}
	// write "BtnLabel"
	err = en.Append(0xa8, 0x42, 0x74, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Section.BtnLabel)
	if err != nil {
		err = msgp.WrapError(err, "Section", "BtnLabel")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *NavbarIdentityConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Home"
	o = append(o, 0x82, 0xa4, 0x48, 0x6f, 0x6d, 0x65)
	// map header, size 2
	// string "Title"
	o = append(o, 0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Home.Title)
	// string "BtnLabel"
	o = append(o, 0xa8, 0x42, 0x74, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c)
	o = msgp.AppendString(o, z.Home.BtnLabel)
	// string "Section"
	o = append(o, 0xa7, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e)
	// map header, size 2
	// string "Title"
	o = append(o, 0x82, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Section.Title)
	// string "BtnLabel"
	o = append(o, 0xa8, 0x42, 0x74, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c)
	o = msgp.AppendString(o, z.Section.BtnLabel)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NavbarIdentityConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Home":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Home")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Home")
					return
				}
				switch msgp.UnsafeString(field) {
				case "Title":
					z.Home.Title, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Home", "Title")
						return
					}
				case "BtnLabel":
					z.Home.BtnLabel, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Home", "BtnLabel")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Home")
						return
					}
				}
			}
		case "Section":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Section")
				return
			}
			for zb0003 > 0 {
				zb0003--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Section")
					return
				}
				switch msgp.UnsafeString(field) {
				case "Title":
					z.Section.Title, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Section", "Title")
						return
					}
				case "BtnLabel":
					z.Section.BtnLabel, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Section", "BtnLabel")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Section")
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NavbarIdentityConfig) Msgsize() (s int) {
	s = 1 + 5 + 1 + 6 + msgp.StringPrefixSize + len(z.Home.Title) + 9 + msgp.StringPrefixSize + len(z.Home.BtnLabel) + 8 + 1 + 6 + msgp.StringPrefixSize + len(z.Section.Title) + 9 + msgp.StringPrefixSize + len(z.Section.BtnLabel)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SearchOptionsConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "IsEnabled":
			z.IsEnabled, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "IsEnabled")
				return
			}
		case "Ranking":
			err = z.Ranking.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Ranking")
				return
			}
		case "Endpoints":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Endpoints")
				return
			}
			if cap(z.Endpoints) >= int(zb0002) {
				z.Endpoints = (z.Endpoints)[:zb0002]
			} else {
				z.Endpoints = make([]string, zb0002)
			}
			for za0001 := range z.Endpoints {
				z.Endpoints[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Endpoints", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SearchOptionsConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "IsEnabled"
	err = en.Append(0x83, 0xa9, 0x49, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteBool(z.IsEnabled)
	if err != nil {
		err = msgp.WrapError(err, "IsEnabled")
		return
	}
	// write "Ranking"
	err = en.Append(0xa7, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = z.Ranking.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Ranking")
		return
	}
	// write "Endpoints"
	err = en.Append(0xa9, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Endpoints)))
	if err != nil {
		err = msgp.WrapError(err, "Endpoints")
		return
	}
	for za0001 := range z.Endpoints {
		err = en.WriteString(z.Endpoints[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Endpoints", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SearchOptionsConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "IsEnabled"
	o = append(o, 0x83, 0xa9, 0x49, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	o = msgp.AppendBool(o, z.IsEnabled)
	// string "Ranking"
	o = append(o, 0xa7, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67)
	o, err = z.Ranking.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Ranking")
		return
	}
	// string "Endpoints"
	o = append(o, 0xa9, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Endpoints)))
	for za0001 := range z.Endpoints {
		o = msgp.AppendString(o, z.Endpoints[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SearchOptionsConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "IsEnabled":
			z.IsEnabled, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsEnabled")
				return
			}
		case "Ranking":
			bts, err = z.Ranking.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ranking")
				return
			}
		case "Endpoints":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Endpoints")
				return
			}
			if cap(z.Endpoints) >= int(zb0002) {
				z.Endpoints = (z.Endpoints)[:zb0002]
			} else {
				z.Endpoints = make([]string, zb0002)
			}
			for za0001 := range z.Endpoints {
				z.Endpoints[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Endpoints", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SearchOptionsConfig) Msgsize() (s int) {
	s = 1 + 10 + msgp.BoolSize + 8 + z.Ranking.Msgsize() + 10 + msgp.ArrayHeaderSize
	for za0001 := range z.Endpoints {
		s += msgp.StringPrefixSize + len(z.Endpoints[za0001])
	}
	return
}


// DecodeMsg implements msgp.Decodable
func (z *SocialCardsConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Background":
			z.Background, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Background")
				return
			}
		case "Gradient":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Gradient")
				return
			}
			if cap(z.Gradient) >= int(zb0002) {
				z.Gradient = (z.Gradient)[:zb0002]
			} else {
				z.Gradient = make([]string, zb0002)
			}
			for za0001 := range z.Gradient {
				z.Gradient[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Gradient", za0001)
					return
				}
			}
		case "Angle":
			z.Angle, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Angle")
				return
			}
		case "TextColor":
			z.TextColor, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "TextColor")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SocialCardsConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "Background"
	err = en.Append(0x84, 0xaa, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.Background)
	if err != nil {
		err = msgp.WrapError(err, "Background")
		return
	}
	// write "Gradient"
	err = en.Append(0xa8, 0x47, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Gradient)))
	if err != nil {
		err = msgp.WrapError(err, "Gradient")
		return
	}
	for za0001 := range z.Gradient {
		err = en.WriteString(z.Gradient[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Gradient", za0001)
			return
		}
	}
	// write "Angle"
	err = en.Append(0xa5, 0x41, 0x6e, 0x67, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Angle)
	if err != nil {
		err = msgp.WrapError(err, "Angle")
		return
	}
	// write "TextColor"
	err = en.Append(0xa9, 0x54, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.TextColor)
	if err != nil {
		err = msgp.WrapError(err, "TextColor")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SocialCardsConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "Background"
	o = append(o, 0x84, 0xaa, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64)
	o = msgp.AppendString(o, z.Background)
	// string "Gradient"
	o = append(o, 0xa8, 0x47, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Gradient)))
	for za0001 := range z.Gradient {
		o = msgp.AppendString(o, z.Gradient[za0001])
	}
	// string "Angle"
	o = append(o, 0xa5, 0x41, 0x6e, 0x67, 0x6c, 0x65)
	o = msgp.AppendInt(o, z.Angle)
	// string "TextColor"
	o = append(o, 0xa9, 0x54, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72)
	o = msgp.AppendString(o, z.TextColor)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SocialCardsConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Background":
			z.Background, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Background")
				return
			}
		case "Gradient":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Gradient")
				return
			}
			if cap(z.Gradient) >= int(zb0002) {
				z.Gradient = (z.Gradient)[:zb0002]
			} else {
				z.Gradient = make([]string, zb0002)
			}
			for za0001 := range z.Gradient {
				z.Gradient[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Gradient", za0001)
					return
				}
			}
		case "Angle":
			z.Angle, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Angle")
				return
			}
		case "TextColor":
			z.TextColor, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TextColor")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SocialCardsConfig) Msgsize() (s int) {
	s = 1 + 11 + msgp.StringPrefixSize + len(z.Background) + 9 + msgp.ArrayHeaderSize
	for za0001 := range z.Gradient {
		s += msgp.StringPrefixSize + len(z.Gradient[za0001])
	}
	s += 6 + msgp.IntSize + 10 + msgp.StringPrefixSize + len(z.TextColor)
	return
}
