// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package models

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *GraphConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "IsEnabled":
			z.IsEnabled, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "IsEnabled")
				return
			}
		case "ShowsTaxonomies":
			z.ShowsTaxonomies, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "ShowsTaxonomies")
				return
			}
		case "MaxNodes":
			z.MaxNodes, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "MaxNodes")
				return
			}
		case "MinTermFrequency":
			z.MinTermFrequency, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "MinTermFrequency")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GraphConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "IsEnabled"
	err = en.Append(0x84, 0xa9, 0x49, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteBool(z.IsEnabled)
	if err != nil {
		err = msgp.WrapError(err, "IsEnabled")
		return
	}
	// write "ShowsTaxonomies"
	err = en.Append(0xaf, 0x53, 0x68, 0x6f, 0x77, 0x73, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x69, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBool(z.ShowsTaxonomies)
	if err != nil {
		err = msgp.WrapError(err, "ShowsTaxonomies")
		return
	}
	// write "MaxNodes"
	err = en.Append(0xa8, 0x4d, 0x61, 0x78, 0x4e, 0x6f, 0x64, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.MaxNodes)
	if err != nil {
		err = msgp.WrapError(err, "MaxNodes")
		return
	}
	// write "MinTermFrequency"
	err = en.Append(0xb0, 0x4d, 0x69, 0x6e, 0x54, 0x65, 0x72, 0x6d, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79)
	if err != nil {
		return
	}
	err = en.WriteInt(z.MinTermFrequency)
	if err != nil {
		err = msgp.WrapError(err, "MinTermFrequency")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GraphConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "IsEnabled"
	o = append(o, 0x84, 0xa9, 0x49, 0x73, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64)
	o = msgp.AppendBool(o, z.IsEnabled)
	// string "ShowsTaxonomies"
	o = append(o, 0xaf, 0x53, 0x68, 0x6f, 0x77, 0x73, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x69, 0x65, 0x73)
	o = msgp.AppendBool(o, z.ShowsTaxonomies)
	// string "MaxNodes"
	o = append(o, 0xa8, 0x4d, 0x61, 0x78, 0x4e, 0x6f, 0x64, 0x65, 0x73)
	o = msgp.AppendInt(o, z.MaxNodes)
	// string "MinTermFrequency"
	o = append(o, 0xb0, 0x4d, 0x69, 0x6e, 0x54, 0x65, 0x72, 0x6d, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79)
	o = msgp.AppendInt(o, z.MinTermFrequency)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GraphConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "IsEnabled":
			z.IsEnabled, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsEnabled")
				return
			}
		case "ShowsTaxonomies":
			z.ShowsTaxonomies, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ShowsTaxonomies")
				return
			}
		case "MaxNodes":
			z.MaxNodes, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MaxNodes")
				return
			}
		case "MinTermFrequency":
			z.MinTermFrequency, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MinTermFrequency")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GraphConfig) Msgsize() (s int) {
	s = 1 + 10 + msgp.BoolSize + 16 + msgp.BoolSize + 9 + msgp.IntSize + 17 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *GraphData) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Nodes":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
			if cap(z.Nodes) >= int(zb0002) {
				z.Nodes = (z.Nodes)[:zb0002]
			} else {
				z.Nodes = make([]GraphNode, zb0002)
			}
			for za0001 := range z.Nodes {
				err = z.Nodes[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Nodes", za0001)
					return
				}
			}
		case "Links":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Links")
				return
			}
			if cap(z.Links) >= int(zb0003) {
				z.Links = (z.Links)[:zb0003]
			} else {
				z.Links = make([]GraphLink, zb0003)
			}
			for za0002 := range z.Links {
				err = z.Links[za0002].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Links", za0002)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GraphData) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Nodes"
	err = en.Append(0x82, 0xa5, 0x4e, 0x6f, 0x64, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Nodes)))
	if err != nil {
		err = msgp.WrapError(err, "Nodes")
		return
	}
	for za0001 := range z.Nodes {
		err = z.Nodes[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Nodes", za0001)
			return
		}
	}
	// write "Links"
	err = en.Append(0xa5, 0x4c, 0x69, 0x6e, 0x6b, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Links)))
	if err != nil {
		err = msgp.WrapError(err, "Links")
		return
	}
	for za0002 := range z.Links {
		err = z.Links[za0002].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Links", za0002)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GraphData) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Nodes"
	o = append(o, 0x82, 0xa5, 0x4e, 0x6f, 0x64, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Nodes)))
	for za0001 := range z.Nodes {
		o, err = z.Nodes[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Nodes", za0001)
			return
		}
	}
	// string "Links"
	o = append(o, 0xa5, 0x4c, 0x69, 0x6e, 0x6b, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Links)))
	for za0002 := range z.Links {
		o, err = z.Links[za0002].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Links", za0002)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GraphData) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Nodes":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
			if cap(z.Nodes) >= int(zb0002) {
				z.Nodes = (z.Nodes)[:zb0002]
			} else {
				z.Nodes = make([]GraphNode, zb0002)
			}
			for za0001 := range z.Nodes {
				bts, err = z.Nodes[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Nodes", za0001)
					return
				}
			}
		case "Links":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Links")
				return
			}
			if cap(z.Links) >= int(zb0003) {
				z.Links = (z.Links)[:zb0003]
			} else {
				z.Links = make([]GraphLink, zb0003)
			}
			for za0002 := range z.Links {
				bts, err = z.Links[za0002].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Links", za0002)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GraphData) Msgsize() (s int) {
	s = 1 + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Nodes {
		s += z.Nodes[za0001].Msgsize()
	}
	s += 6 + msgp.ArrayHeaderSize
	for za0002 := range z.Links {
		s += z.Links[za0002].Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *GraphLink) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Source":
			z.Source, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Source")
				return
			}
		case "Target":
			z.Target, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Target")
				return
			}
		case "Type":
			z.Type, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "Weight":
			z.Weight, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Weight")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GraphLink) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "Source"
	err = en.Append(0x84, 0xa6, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Source)
	if err != nil {
		err = msgp.WrapError(err, "Source")
		return
	}
	// write "Target"
	err = en.Append(0xa6, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Target)
	if err != nil {
		err = msgp.WrapError(err, "Target")
		return
	}
	// write "Type"
	err = en.Append(0xa4, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Type)
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "Weight"
	err = en.Append(0xa6, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Weight)
	if err != nil {
		err = msgp.WrapError(err, "Weight")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GraphLink) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "Source"
	o = append(o, 0x84, 0xa6, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65)
	o = msgp.AppendString(o, z.Source)
	// string "Target"
	o = append(o, 0xa6, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74)
	o = msgp.AppendString(o, z.Target)
	// string "Type"
	o = append(o, 0xa4, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendString(o, z.Type)
	// string "Weight"
	o = append(o, 0xa6, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74)
	o = msgp.AppendFloat64(o, z.Weight)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GraphLink) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Source":
			z.Source, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Source")
				return
			}
		case "Target":
			z.Target, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Target")
				return
			}
		case "Type":
			z.Type, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "Weight":
			z.Weight, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Weight")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GraphLink) Msgsize() (s int) {
	s = 1 + 7 + msgp.StringPrefixSize + len(z.Source) + 7 + msgp.StringPrefixSize + len(z.Target) + 5 + msgp.StringPrefixSize + len(z.Type) + 7 + msgp.Float64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *GraphNode) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Label":
			z.Label, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Label")
				return
			}
		case "Group":
			z.Group, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Group")
				return
			}
		case "Value":
			z.Value, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "URL":
			z.URL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "Date":
			z.Date, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Date")
				return
			}
		case "ReadingTime":
			z.ReadingTime, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "ReadingTime")
				return
			}
		case "Excerpt":
			z.Excerpt, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Excerpt")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GraphNode) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 8
	// write "ID"
	err = en.Append(0x88, 0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "Label"
	err = en.Append(0xa5, 0x4c, 0x61, 0x62, 0x65, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Label)
	if err != nil {
		err = msgp.WrapError(err, "Label")
		return
	}
	// write "Group"
	err = en.Append(0xa5, 0x47, 0x72, 0x6f, 0x75, 0x70)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Group)
	if err != nil {
		err = msgp.WrapError(err, "Group")
		return
	}
	// write "Value"
	err = en.Append(0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	// write "URL"
	err = en.Append(0xa3, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.URL)
	if err != nil {
		err = msgp.WrapError(err, "URL")
		return
	}
	// write "Date"
	err = en.Append(0xa4, 0x44, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Date)
	if err != nil {
		err = msgp.WrapError(err, "Date")
		return
	}
	// write "ReadingTime"
	err = en.Append(0xab, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.ReadingTime)
	if err != nil {
		err = msgp.WrapError(err, "ReadingTime")
		return
	}
	// write "Excerpt"
	err = en.Append(0xa7, 0x45, 0x78, 0x63, 0x65, 0x72, 0x70, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Excerpt)
	if err != nil {
		err = msgp.WrapError(err, "Excerpt")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GraphNode) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 8
	// string "ID"
	o = append(o, 0x88, 0xa2, 0x49, 0x44)
	o = msgp.AppendString(o, z.ID)
	// string "Label"
	o = append(o, 0xa5, 0x4c, 0x61, 0x62, 0x65, 0x6c)
	o = msgp.AppendString(o, z.Label)
	// string "Group"
	o = append(o, 0xa5, 0x47, 0x72, 0x6f, 0x75, 0x70)
	o = msgp.AppendInt(o, z.Group)
	// string "Value"
	o = append(o, 0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
	o = msgp.AppendInt(o, z.Value)
	// string "URL"
	o = append(o, 0xa3, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.URL)
	// string "Date"
	o = append(o, 0xa4, 0x44, 0x61, 0x74, 0x65)
	o = msgp.AppendString(o, z.Date)
	// string "ReadingTime"
	o = append(o, 0xab, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65)
	o = msgp.AppendInt(o, z.ReadingTime)
	// string "Excerpt"
	o = append(o, 0xa7, 0x45, 0x78, 0x63, 0x65, 0x72, 0x70, 0x74)
	o = msgp.AppendString(o, z.Excerpt)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GraphNode) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Label":
			z.Label, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Label")
				return
			}
		case "Group":
			z.Group, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Group")
				return
			}
		case "Value":
			z.Value, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "URL":
			z.URL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "Date":
			z.Date, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Date")
				return
			}
		case "ReadingTime":
			z.ReadingTime, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ReadingTime")
				return
			}
		case "Excerpt":
			z.Excerpt, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Excerpt")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GraphNode) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 6 + msgp.StringPrefixSize + len(z.Label) + 6 + msgp.IntSize + 6 + msgp.IntSize + 4 + msgp.StringPrefixSize + len(z.URL) + 5 + msgp.StringPrefixSize + len(z.Date) + 12 + msgp.IntSize + 8 + msgp.StringPrefixSize + len(z.Excerpt)
	return
}
