// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package models

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *IndexedPost) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Record":
			err = z.Record.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Record")
				return
			}
		case "SourcePath":
			z.SourcePath, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SourcePath")
				return
			}
		case "WordFreqs":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "WordFreqs")
				return
			}
			if z.WordFreqs == nil {
				z.WordFreqs = make(map[string]int, zb0002)
			} else if len(z.WordFreqs) > 0 {
				clear(z.WordFreqs)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "WordFreqs")
					return
				}
				var za0002 int
				za0002, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "WordFreqs", za0001)
					return
				}
				z.WordFreqs[za0001] = za0002
			}
		case "DocLen":
			z.DocLen, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "DocLen")
				return
			}
		case "StemMap":
			var zb0003 uint32
			zb0003, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "StemMap")
				return
			}
			if z.StemMap == nil {
				z.StemMap = make(map[string]string, zb0003)
			} else if len(z.StemMap) > 0 {
				clear(z.StemMap)
			}
			for zb0003 > 0 {
				zb0003--
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "StemMap")
					return
				}
				var za0004 string
				za0004, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "StemMap", za0003)
					return
				}
				z.StemMap[za0003] = za0004
			}
		case "PositionalIndex":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "PositionalIndex")
				return
			}
			if z.PositionalIndex == nil {
				z.PositionalIndex = make(map[string][]int, zb0004)
			} else if len(z.PositionalIndex) > 0 {
				clear(z.PositionalIndex)
			}
			for zb0004 > 0 {
				zb0004--
				var za0005 string
				za0005, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex")
					return
				}
				var za0006 []int
				var zb0005 uint32
				zb0005, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex", za0005)
					return
				}
				if cap(za0006) >= int(zb0005) {
					za0006 = (za0006)[:zb0005]
				} else {
					za0006 = make([]int, zb0005)
				}
				for za0007 := range za0006 {
					za0006[za0007], err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "PositionalIndex", za0005, za0007)
						return
					}
				}
				z.PositionalIndex[za0005] = za0006
			}
		case "ByteOffsets":
			var zb0006 uint32
			zb0006, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "ByteOffsets")
				return
			}
			if z.ByteOffsets == nil {
				z.ByteOffsets = make(map[string][]int, zb0006)
			} else if len(z.ByteOffsets) > 0 {
				clear(z.ByteOffsets)
			}
			for zb0006 > 0 {
				zb0006--
				var za0008 string
				za0008, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "ByteOffsets")
					return
				}
				var za0009 []int
				var zb0007 uint32
				zb0007, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "ByteOffsets", za0008)
					return
				}
				if cap(za0009) >= int(zb0007) {
					za0009 = (za0009)[:zb0007]
				} else {
					za0009 = make([]int, zb0007)
				}
				for za0010 := range za0009 {
					za0009[za0010], err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "ByteOffsets", za0008, za0010)
						return
					}
				}
				z.ByteOffsets[za0008] = za0009
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *IndexedPost) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "Record"
	err = en.Append(0x87, 0xa6, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64)
	if err != nil {
		return
	}
	err = z.Record.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Record")
		return
	}
	// write "SourcePath"
	err = en.Append(0xaa, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.SourcePath)
	if err != nil {
		err = msgp.WrapError(err, "SourcePath")
		return
	}
	// write "WordFreqs"
	err = en.Append(0xa9, 0x57, 0x6f, 0x72, 0x64, 0x46, 0x72, 0x65, 0x71, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.WordFreqs)))
	if err != nil {
		err = msgp.WrapError(err, "WordFreqs")
		return
	}
	for za0001, za0002 := range z.WordFreqs {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "WordFreqs")
			return
		}
		err = en.WriteInt(za0002)
		if err != nil {
			err = msgp.WrapError(err, "WordFreqs", za0001)
			return
		}
	}
	// write "DocLen"
	err = en.Append(0xa6, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt(z.DocLen)
	if err != nil {
		err = msgp.WrapError(err, "DocLen")
		return
	}
	// write "StemMap"
	err = en.Append(0xa7, 0x53, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.StemMap)))
	if err != nil {
		err = msgp.WrapError(err, "StemMap")
		return
	}
	for za0003, za0004 := range z.StemMap {
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "StemMap")
			return
		}
		err = en.WriteString(za0004)
		if err != nil {
			err = msgp.WrapError(err, "StemMap", za0003)
			return
		}
	}
	// write "PositionalIndex"
	err = en.Append(0xaf, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.PositionalIndex)))
	if err != nil {
		err = msgp.WrapError(err, "PositionalIndex")
		return
	}
	for za0005, za0006 := range z.PositionalIndex {
		err = en.WriteString(za0005)
		if err != nil {
			err = msgp.WrapError(err, "PositionalIndex")
			return
		}
		err = en.WriteArrayHeader(uint32(len(za0006)))
		if err != nil {
			err = msgp.WrapError(err, "PositionalIndex", za0005)
			return
		}
		for za0007 := range za0006 {
			err = en.WriteInt(za0006[za0007])
			if err != nil {
				err = msgp.WrapError(err, "PositionalIndex", za0005, za0007)
				return
			}
		}
	}
	// write "ByteOffsets"
	err = en.Append(0xab, 0x42, 0x79, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.ByteOffsets)))
	if err != nil {
		err = msgp.WrapError(err, "ByteOffsets")
		return
	}
	for za0008, za0009 := range z.ByteOffsets {
		err = en.WriteString(za0008)
		if err != nil {
			err = msgp.WrapError(err, "ByteOffsets")
			return
		}
		err = en.WriteArrayHeader(uint32(len(za0009)))
		if err != nil {
			err = msgp.WrapError(err, "ByteOffsets", za0008)
			return
		}
		for za0010 := range za0009 {
			err = en.WriteInt(za0009[za0010])
			if err != nil {
				err = msgp.WrapError(err, "ByteOffsets", za0008, za0010)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *IndexedPost) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "Record"
	o = append(o, 0x87, 0xa6, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64)
	o, err = z.Record.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Record")
		return
	}
	// string "SourcePath"
	o = append(o, 0xaa, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68)
	o = msgp.AppendString(o, z.SourcePath)
	// string "WordFreqs"
	o = append(o, 0xa9, 0x57, 0x6f, 0x72, 0x64, 0x46, 0x72, 0x65, 0x71, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.WordFreqs)))
	for za0001, za0002 := range z.WordFreqs {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendInt(o, za0002)
	}
	// string "DocLen"
	o = append(o, 0xa6, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e)
	o = msgp.AppendInt(o, z.DocLen)
	// string "StemMap"
	o = append(o, 0xa7, 0x53, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x70)
	o = msgp.AppendMapHeader(o, uint32(len(z.StemMap)))
	for za0003, za0004 := range z.StemMap {
		o = msgp.AppendString(o, za0003)
		o = msgp.AppendString(o, za0004)
	}
	// string "PositionalIndex"
	o = append(o, 0xaf, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78)
	o = msgp.AppendMapHeader(o, uint32(len(z.PositionalIndex)))
	for za0005, za0006 := range z.PositionalIndex {
		o = msgp.AppendString(o, za0005)
		o = msgp.AppendArrayHeader(o, uint32(len(za0006)))
		for za0007 := range za0006 {
			o = msgp.AppendInt(o, za0006[za0007])
		}
	}
	// string "ByteOffsets"
	o = append(o, 0xab, 0x42, 0x79, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.ByteOffsets)))
	for za0008, za0009 := range z.ByteOffsets {
		o = msgp.AppendString(o, za0008)
		o = msgp.AppendArrayHeader(o, uint32(len(za0009)))
		for za0010 := range za0009 {
			o = msgp.AppendInt(o, za0009[za0010])
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *IndexedPost) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Record":
			bts, err = z.Record.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Record")
				return
			}
		case "SourcePath":
			z.SourcePath, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SourcePath")
				return
			}
		case "WordFreqs":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WordFreqs")
				return
			}
			if z.WordFreqs == nil {
				z.WordFreqs = make(map[string]int, zb0002)
			} else if len(z.WordFreqs) > 0 {
				clear(z.WordFreqs)
			}
			for zb0002 > 0 {
				var za0002 int
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "WordFreqs")
					return
				}
				za0002, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "WordFreqs", za0001)
					return
				}
				z.WordFreqs[za0001] = za0002
			}
		case "DocLen":
			z.DocLen, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DocLen")
				return
			}
		case "StemMap":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StemMap")
				return
			}
			if z.StemMap == nil {
				z.StemMap = make(map[string]string, zb0003)
			} else if len(z.StemMap) > 0 {
				clear(z.StemMap)
			}
			for zb0003 > 0 {
				var za0004 string
				zb0003--
				var za0003 string
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StemMap")
					return
				}
				za0004, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StemMap", za0003)
					return
				}
				z.StemMap[za0003] = za0004
			}
		case "PositionalIndex":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PositionalIndex")
				return
			}
			if z.PositionalIndex == nil {
				z.PositionalIndex = make(map[string][]int, zb0004)
			} else if len(z.PositionalIndex) > 0 {
				clear(z.PositionalIndex)
			}
			for zb0004 > 0 {
				var za0006 []int
				zb0004--
				var za0005 string
				za0005, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex")
					return
				}
				var zb0005 uint32
				zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex", za0005)
					return
				}
				if cap(za0006) >= int(zb0005) {
					za0006 = (za0006)[:zb0005]
				} else {
					za0006 = make([]int, zb0005)
				}
				for za0007 := range za0006 {
					za0006[za0007], bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "PositionalIndex", za0005, za0007)
						return
					}
				}
				z.PositionalIndex[za0005] = za0006
			}
		case "ByteOffsets":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ByteOffsets")
				return
			}
			if z.ByteOffsets == nil {
				z.ByteOffsets = make(map[string][]int, zb0006)
			} else if len(z.ByteOffsets) > 0 {
				clear(z.ByteOffsets)
			}
			for zb0006 > 0 {
				var za0009 []int
				zb0006--
				var za0008 string
				za0008, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ByteOffsets")
					return
				}
				var zb0007 uint32
				zb0007, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ByteOffsets", za0008)
					return
				}
				if cap(za0009) >= int(zb0007) {
					za0009 = (za0009)[:zb0007]
				} else {
					za0009 = make([]int, zb0007)
				}
				for za0010 := range za0009 {
					za0009[za0010], bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "ByteOffsets", za0008, za0010)
						return
					}
				}
				z.ByteOffsets[za0008] = za0009
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *IndexedPost) Msgsize() (s int) {
	s = 1 + 7 + z.Record.Msgsize() + 11 + msgp.StringPrefixSize + len(z.SourcePath) + 10 + msgp.MapHeaderSize
	if z.WordFreqs != nil {
		for za0001, za0002 := range z.WordFreqs {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.IntSize
		}
	}
	s += 7 + msgp.IntSize + 8 + msgp.MapHeaderSize
	if z.StemMap != nil {
		for za0003, za0004 := range z.StemMap {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.StringPrefixSize + len(za0004)
		}
	}
	s += 16 + msgp.MapHeaderSize
	if z.PositionalIndex != nil {
		for za0005, za0006 := range z.PositionalIndex {
			_ = za0006
			s += msgp.StringPrefixSize + len(za0005) + msgp.ArrayHeaderSize + (len(za0006) * (msgp.IntSize))
		}
	}
	s += 12 + msgp.MapHeaderSize
	if z.ByteOffsets != nil {
		for za0008, za0009 := range z.ByteOffsets {
			_ = za0009
			s += msgp.StringPrefixSize + len(za0008) + msgp.ArrayHeaderSize + (len(za0009) * (msgp.IntSize))
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PostRecord) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "NormalizedTitle":
			z.NormalizedTitle, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "NormalizedTitle")
				return
			}
		case "Link":
			z.Link, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Link")
				return
			}
		case "Description":
			z.Description, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Description")
				return
			}
		case "Tags":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Tags")
				return
			}
			if cap(z.Tags) >= int(zb0002) {
				z.Tags = (z.Tags)[:zb0002]
			} else {
				z.Tags = make([]string, zb0002)
			}
			for za0001 := range z.Tags {
				z.Tags[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Tags", za0001)
					return
				}
			}
		case "NormalizedTags":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "NormalizedTags")
				return
			}
			if cap(z.NormalizedTags) >= int(zb0003) {
				z.NormalizedTags = (z.NormalizedTags)[:zb0003]
			} else {
				z.NormalizedTags = make([]string, zb0003)
			}
			for za0002 := range z.NormalizedTags {
				z.NormalizedTags[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "NormalizedTags", za0002)
					return
				}
			}
		case "Content":
			z.Content, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "Version":
			z.Version, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PostRecord) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 9
	// write "ID"
	err = en.Append(0x89, 0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteInt(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "Title"
	err = en.Append(0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Title)
	if err != nil {
		err = msgp.WrapError(err, "Title")
		return
	}
	// write "NormalizedTitle"
	err = en.Append(0xaf, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.NormalizedTitle)
	if err != nil {
		err = msgp.WrapError(err, "NormalizedTitle")
		return
	}
	// write "Link"
	err = en.Append(0xa4, 0x4c, 0x69, 0x6e, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteString(z.Link)
	if err != nil {
		err = msgp.WrapError(err, "Link")
		return
	}
	// write "Description"
	err = en.Append(0xab, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Description)
	if err != nil {
		err = msgp.WrapError(err, "Description")
		return
	}
	// write "Tags"
	err = en.Append(0xa4, 0x54, 0x61, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Tags)))
	if err != nil {
		err = msgp.WrapError(err, "Tags")
		return
	}
	for za0001 := range z.Tags {
		err = en.WriteString(z.Tags[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Tags", za0001)
			return
		}
	}
	// write "NormalizedTags"
	err = en.Append(0xae, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x61, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.NormalizedTags)))
	if err != nil {
		err = msgp.WrapError(err, "NormalizedTags")
		return
	}
	for za0002 := range z.NormalizedTags {
		err = en.WriteString(z.NormalizedTags[za0002])
		if err != nil {
			err = msgp.WrapError(err, "NormalizedTags", za0002)
			return
		}
	}
	// write "Content"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Content)
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	// write "Version"
	err = en.Append(0xa7, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Version)
	if err != nil {
		err = msgp.WrapError(err, "Version")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PostRecord) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 9
	// string "ID"
	o = append(o, 0x89, 0xa2, 0x49, 0x44)
	o = msgp.AppendInt(o, z.ID)
	// string "Title"
	o = append(o, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Title)
	// string "NormalizedTitle"
	o = append(o, 0xaf, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.NormalizedTitle)
	// string "Link"
	o = append(o, 0xa4, 0x4c, 0x69, 0x6e, 0x6b)
	o = msgp.AppendString(o, z.Link)
	// string "Description"
	o = append(o, 0xab, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Description)
	// string "Tags"
	o = append(o, 0xa4, 0x54, 0x61, 0x67, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Tags)))
	for za0001 := range z.Tags {
		o = msgp.AppendString(o, z.Tags[za0001])
	}
	// string "NormalizedTags"
	o = append(o, 0xae, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x61, 0x67, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.NormalizedTags)))
	for za0002 := range z.NormalizedTags {
		o = msgp.AppendString(o, z.NormalizedTags[za0002])
	}
	// string "Content"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	o = msgp.AppendString(o, z.Content)
	// string "Version"
	o = append(o, 0xa7, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Version)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PostRecord) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "NormalizedTitle":
			z.NormalizedTitle, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NormalizedTitle")
				return
			}
		case "Link":
			z.Link, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Link")
				return
			}
		case "Description":
			z.Description, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Description")
				return
			}
		case "Tags":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tags")
				return
			}
			if cap(z.Tags) >= int(zb0002) {
				z.Tags = (z.Tags)[:zb0002]
			} else {
				z.Tags = make([]string, zb0002)
			}
			for za0001 := range z.Tags {
				z.Tags[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Tags", za0001)
					return
				}
			}
		case "NormalizedTags":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NormalizedTags")
				return
			}
			if cap(z.NormalizedTags) >= int(zb0003) {
				z.NormalizedTags = (z.NormalizedTags)[:zb0003]
			} else {
				z.NormalizedTags = make([]string, zb0003)
			}
			for za0002 := range z.NormalizedTags {
				z.NormalizedTags[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "NormalizedTags", za0002)
					return
				}
			}
		case "Content":
			z.Content, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "Version":
			z.Version, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PostRecord) Msgsize() (s int) {
	s = 1 + 3 + msgp.IntSize + 6 + msgp.StringPrefixSize + len(z.Title) + 16 + msgp.StringPrefixSize + len(z.NormalizedTitle) + 5 + msgp.StringPrefixSize + len(z.Link) + 12 + msgp.StringPrefixSize + len(z.Description) + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.Tags {
		s += msgp.StringPrefixSize + len(z.Tags[za0001])
	}
	s += 15 + msgp.ArrayHeaderSize
	for za0002 := range z.NormalizedTags {
		s += msgp.StringPrefixSize + len(z.NormalizedTags[za0002])
	}
	s += 8 + msgp.StringPrefixSize + len(z.Content) + 8 + msgp.StringPrefixSize + len(z.Version)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SearchIndex) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SchemaVersion":
			z.SchemaVersion, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "SchemaVersion")
				return
			}
		case "Posts":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Posts")
				return
			}
			if cap(z.Posts) >= int(zb0002) {
				z.Posts = (z.Posts)[:zb0002]
			} else {
				z.Posts = make([]PostRecord, zb0002)
			}
			for za0001 := range z.Posts {
				err = z.Posts[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Posts", za0001)
					return
				}
			}
		case "DocLens":
			var zb0003 uint32
			zb0003, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "DocLens")
				return
			}
			if z.DocLens == nil {
				z.DocLens = make(map[string]int64, zb0003)
			} else if len(z.DocLens) > 0 {
				clear(z.DocLens)
			}
			for zb0003 > 0 {
				zb0003--
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "DocLens")
					return
				}
				var za0003 int64
				za0003, err = dc.ReadInt64()
				if err != nil {
					err = msgp.WrapError(err, "DocLens", za0002)
					return
				}
				z.DocLens[za0002] = za0003
			}
		case "AvgDocLen":
			z.AvgDocLen, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "AvgDocLen")
				return
			}
		case "TotalDocs":
			z.TotalDocs, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "TotalDocs")
				return
			}
		case "StemMap":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "StemMap")
				return
			}
			if z.StemMap == nil {
				z.StemMap = make(map[string][]string, zb0004)
			} else if len(z.StemMap) > 0 {
				clear(z.StemMap)
			}
			for zb0004 > 0 {
				zb0004--
				var za0004 string
				za0004, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "StemMap")
					return
				}
				var za0005 []string
				var zb0005 uint32
				zb0005, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "StemMap", za0004)
					return
				}
				if cap(za0005) >= int(zb0005) {
					za0005 = (za0005)[:zb0005]
				} else {
					za0005 = make([]string, zb0005)
				}
				for za0006 := range za0005 {
					za0005[za0006], err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "StemMap", za0004, za0006)
						return
					}
				}
				z.StemMap[za0004] = za0005
			}
		case "NgramIndex":
			var zb0006 uint32
			zb0006, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "NgramIndex")
				return
			}
			if z.NgramIndex == nil {
				z.NgramIndex = make(map[string][]string, zb0006)
			} else if len(z.NgramIndex) > 0 {
				clear(z.NgramIndex)
			}
			for zb0006 > 0 {
				zb0006--
				var za0007 string
				za0007, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "NgramIndex")
					return
				}
				var za0008 []string
				var zb0007 uint32
				zb0007, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "NgramIndex", za0007)
					return
				}
				if cap(za0008) >= int(zb0007) {
					za0008 = (za0008)[:zb0007]
				} else {
					za0008 = make([]string, zb0007)
				}
				for za0009 := range za0008 {
					za0008[za0009], err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "NgramIndex", za0007, za0009)
						return
					}
				}
				z.NgramIndex[za0007] = za0008
			}
		case "Inverted":
			var zb0008 uint32
			zb0008, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Inverted")
				return
			}
			if z.Inverted == nil {
				z.Inverted = make(map[string]map[string][]int, zb0008)
			} else if len(z.Inverted) > 0 {
				clear(z.Inverted)
			}
			for zb0008 > 0 {
				zb0008--
				var za0010 string
				za0010, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Inverted")
					return
				}
				var za0011 map[string][]int
				var zb0009 uint32
				zb0009, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Inverted", za0010)
					return
				}
				if za0011 == nil {
					za0011 = make(map[string][]int, zb0009)
				} else if len(za0011) > 0 {
					clear(za0011)
				}
				for zb0009 > 0 {
					zb0009--
					var za0012 string
					za0012, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Inverted", za0010)
						return
					}
					var za0013 []int
					var zb0010 uint32
					zb0010, err = dc.ReadArrayHeader()
					if err != nil {
						err = msgp.WrapError(err, "Inverted", za0010, za0012)
						return
					}
					if cap(za0013) >= int(zb0010) {
						za0013 = (za0013)[:zb0010]
					} else {
						za0013 = make([]int, zb0010)
					}
					for za0014 := range za0013 {
						za0013[za0014], err = dc.ReadInt()
						if err != nil {
							err = msgp.WrapError(err, "Inverted", za0010, za0012, za0014)
							return
						}
					}
					za0011[za0012] = za0013
				}
				z.Inverted[za0010] = za0011
			}
		case "Offsets":
			var zb0011 uint32
			zb0011, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Offsets")
				return
			}
			if z.Offsets == nil {
				z.Offsets = make(map[string]map[string][]int, zb0011)
			} else if len(z.Offsets) > 0 {
				clear(z.Offsets)
			}
			for zb0011 > 0 {
				zb0011--
				var za0015 string
				za0015, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Offsets")
					return
				}
				var za0016 map[string][]int
				var zb0012 uint32
				zb0012, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Offsets", za0015)
					return
				}
				if za0016 == nil {
					za0016 = make(map[string][]int, zb0012)
				} else if len(za0016) > 0 {
					clear(za0016)
				}
				for zb0012 > 0 {
					zb0012--
					var za0017 string
					za0017, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Offsets", za0015)
						return
					}
					var za0018 []int
					var zb0013 uint32
					zb0013, err = dc.ReadArrayHeader()
					if err != nil {
						err = msgp.WrapError(err, "Offsets", za0015, za0017)
						return
					}
					if cap(za0018) >= int(zb0013) {
						za0018 = (za0018)[:zb0013]
					} else {
						za0018 = make([]int, zb0013)
					}
					for za0019 := range za0018 {
						za0018[za0019], err = dc.ReadInt()
						if err != nil {
							err = msgp.WrapError(err, "Offsets", za0015, za0017, za0019)
							return
						}
					}
					za0016[za0017] = za0018
				}
				z.Offsets[za0015] = za0016
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SearchIndex) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 9
	// write "SchemaVersion"
	err = en.Append(0x89, 0xad, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.SchemaVersion)
	if err != nil {
		err = msgp.WrapError(err, "SchemaVersion")
		return
	}
	// write "Posts"
	err = en.Append(0xa5, 0x50, 0x6f, 0x73, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Posts)))
	if err != nil {
		err = msgp.WrapError(err, "Posts")
		return
	}
	for za0001 := range z.Posts {
		err = z.Posts[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Posts", za0001)
			return
		}
	}
	// write "DocLens"
	err = en.Append(0xa7, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.DocLens)))
	if err != nil {
		err = msgp.WrapError(err, "DocLens")
		return
	}
	for za0002, za0003 := range z.DocLens {
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "DocLens")
			return
		}
		err = en.WriteInt64(za0003)
		if err != nil {
			err = msgp.WrapError(err, "DocLens", za0002)
			return
		}
	}
	// write "AvgDocLen"
	err = en.Append(0xa9, 0x41, 0x76, 0x67, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.AvgDocLen)
	if err != nil {
		err = msgp.WrapError(err, "AvgDocLen")
		return
	}
	// write "TotalDocs"
	err = en.Append(0xa9, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x6f, 0x63, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.TotalDocs)
	if err != nil {
		err = msgp.WrapError(err, "TotalDocs")
		return
	}
	// write "StemMap"
	err = en.Append(0xa7, 0x53, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.StemMap)))
	if err != nil {
		err = msgp.WrapError(err, "StemMap")
		return
	}
	for za0004, za0005 := range z.StemMap {
		err = en.WriteString(za0004)
		if err != nil {
			err = msgp.WrapError(err, "StemMap")
			return
		}
		err = en.WriteArrayHeader(uint32(len(za0005)))
		if err != nil {
			err = msgp.WrapError(err, "StemMap", za0004)
			return
		}
		for za0006 := range za0005 {
			err = en.WriteString(za0005[za0006])
			if err != nil {
				err = msgp.WrapError(err, "StemMap", za0004, za0006)
				return
			}
		}
	}
	// write "NgramIndex"
	err = en.Append(0xaa, 0x4e, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.NgramIndex)))
	if err != nil {
		err = msgp.WrapError(err, "NgramIndex")
		return
	}
	for za0007, za0008 := range z.NgramIndex {
		err = en.WriteString(za0007)
		if err != nil {
			err = msgp.WrapError(err, "NgramIndex")
			return
		}
		err = en.WriteArrayHeader(uint32(len(za0008)))
		if err != nil {
			err = msgp.WrapError(err, "NgramIndex", za0007)
			return
		}
		for za0009 := range za0008 {
			err = en.WriteString(za0008[za0009])
			if err != nil {
				err = msgp.WrapError(err, "NgramIndex", za0007, za0009)
				return
			}
		}
	}
	// write "Inverted"
	err = en.Append(0xa8, 0x49, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Inverted)))
	if err != nil {
		err = msgp.WrapError(err, "Inverted")
		return
	}
	for za0010, za0011 := range z.Inverted {
		err = en.WriteString(za0010)
		if err != nil {
			err = msgp.WrapError(err, "Inverted")
			return
		}
		err = en.WriteMapHeader(uint32(len(za0011)))
		if err != nil {
			err = msgp.WrapError(err, "Inverted", za0010)
			return
		}
		for za0012, za0013 := range za0011 {
			err = en.WriteString(za0012)
			if err != nil {
				err = msgp.WrapError(err, "Inverted", za0010)
				return
			}
			err = en.WriteArrayHeader(uint32(len(za0013)))
			if err != nil {
				err = msgp.WrapError(err, "Inverted", za0010, za0012)
				return
			}
			for za0014 := range za0013 {
				err = en.WriteInt(za0013[za0014])
				if err != nil {
					err = msgp.WrapError(err, "Inverted", za0010, za0012, za0014)
					return
				}
			}
		}
	}
	// write "Offsets"
	err = en.Append(0xa7, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Offsets)))
	if err != nil {
		err = msgp.WrapError(err, "Offsets")
		return
	}
	for za0015, za0016 := range z.Offsets {
		err = en.WriteString(za0015)
		if err != nil {
			err = msgp.WrapError(err, "Offsets")
			return
		}
		err = en.WriteMapHeader(uint32(len(za0016)))
		if err != nil {
			err = msgp.WrapError(err, "Offsets", za0015)
			return
		}
		for za0017, za0018 := range za0016 {
			err = en.WriteString(za0017)
			if err != nil {
				err = msgp.WrapError(err, "Offsets", za0015)
				return
			}
			err = en.WriteArrayHeader(uint32(len(za0018)))
			if err != nil {
				err = msgp.WrapError(err, "Offsets", za0015, za0017)
				return
			}
			for za0019 := range za0018 {
				err = en.WriteInt(za0018[za0019])
				if err != nil {
					err = msgp.WrapError(err, "Offsets", za0015, za0017, za0019)
					return
				}
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SearchIndex) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 9
	// string "SchemaVersion"
	o = append(o, 0x89, 0xad, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendInt64(o, z.SchemaVersion)
	// string "Posts"
	o = append(o, 0xa5, 0x50, 0x6f, 0x73, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Posts)))
	for za0001 := range z.Posts {
		o, err = z.Posts[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Posts", za0001)
			return
		}
	}
	// string "DocLens"
	o = append(o, 0xa7, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.DocLens)))
	for za0002, za0003 := range z.DocLens {
		o = msgp.AppendString(o, za0002)
		o = msgp.AppendInt64(o, za0003)
	}
	// string "AvgDocLen"
	o = append(o, 0xa9, 0x41, 0x76, 0x67, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e)
	o = msgp.AppendFloat64(o, z.AvgDocLen)
	// string "TotalDocs"
	o = append(o, 0xa9, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x6f, 0x63, 0x73)
	o = msgp.AppendInt64(o, z.TotalDocs)
	// string "StemMap"
	o = append(o, 0xa7, 0x53, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x70)
	o = msgp.AppendMapHeader(o, uint32(len(z.StemMap)))
	for za0004, za0005 := range z.StemMap {
		o = msgp.AppendString(o, za0004)
		o = msgp.AppendArrayHeader(o, uint32(len(za0005)))
		for za0006 := range za0005 {
			o = msgp.AppendString(o, za0005[za0006])
		}
	}
	// string "NgramIndex"
	o = append(o, 0xaa, 0x4e, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x64, 0x65, 0x78)
	o = msgp.AppendMapHeader(o, uint32(len(z.NgramIndex)))
	for za0007, za0008 := range z.NgramIndex {
		o = msgp.AppendString(o, za0007)
		o = msgp.AppendArrayHeader(o, uint32(len(za0008)))
		for za0009 := range za0008 {
			o = msgp.AppendString(o, za0008[za0009])
		}
	}
	// string "Inverted"
	o = append(o, 0xa8, 0x49, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x64)
	o = msgp.AppendMapHeader(o, uint32(len(z.Inverted)))
	for za0010, za0011 := range z.Inverted {
		o = msgp.AppendString(o, za0010)
		o = msgp.AppendMapHeader(o, uint32(len(za0011)))
		for za0012, za0013 := range za0011 {
			o = msgp.AppendString(o, za0012)
			o = msgp.AppendArrayHeader(o, uint32(len(za0013)))
			for za0014 := range za0013 {
				o = msgp.AppendInt(o, za0013[za0014])
			}
		}
	}
	// string "Offsets"
	o = append(o, 0xa7, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Offsets)))
	for za0015, za0016 := range z.Offsets {
		o = msgp.AppendString(o, za0015)
		o = msgp.AppendMapHeader(o, uint32(len(za0016)))
		for za0017, za0018 := range za0016 {
			o = msgp.AppendString(o, za0017)
			o = msgp.AppendArrayHeader(o, uint32(len(za0018)))
			for za0019 := range za0018 {
				o = msgp.AppendInt(o, za0018[za0019])
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SearchIndex) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SchemaVersion":
			z.SchemaVersion, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SchemaVersion")
				return
			}
		case "Posts":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Posts")
				return
			}
			if cap(z.Posts) >= int(zb0002) {
				z.Posts = (z.Posts)[:zb0002]
			} else {
				z.Posts = make([]PostRecord, zb0002)
			}
			for za0001 := range z.Posts {
				bts, err = z.Posts[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Posts", za0001)
					return
				}
			}
		case "DocLens":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DocLens")
				return
			}
			if z.DocLens == nil {
				z.DocLens = make(map[string]int64, zb0003)
			} else if len(z.DocLens) > 0 {
				clear(z.DocLens)
			}
			for zb0003 > 0 {
				var za0003 int64
				zb0003--
				var za0002 string
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "DocLens")
					return
				}
				za0003, bts, err = msgp.ReadInt64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "DocLens", za0002)
					return
				}
				z.DocLens[za0002] = za0003
			}
		case "AvgDocLen":
			z.AvgDocLen, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AvgDocLen")
				return
			}
		case "TotalDocs":
			z.TotalDocs, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalDocs")
				return
			}
		case "StemMap":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StemMap")
				return
			}
			if z.StemMap == nil {
				z.StemMap = make(map[string][]string, zb0004)
			} else if len(z.StemMap) > 0 {
				clear(z.StemMap)
			}
			for zb0004 > 0 {
				var za0005 []string
				zb0004--
				var za0004 string
				za0004, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StemMap")
					return
				}
				var zb0005 uint32
				zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StemMap", za0004)
					return
				}
				if cap(za0005) >= int(zb0005) {
					za0005 = (za0005)[:zb0005]
				} else {
					za0005 = make([]string, zb0005)
				}
				for za0006 := range za0005 {
					za0005[za0006], bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "StemMap", za0004, za0006)
						return
					}
				}
				z.StemMap[za0004] = za0005
			}
		case "NgramIndex":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NgramIndex")
				return
			}
			if z.NgramIndex == nil {
				z.NgramIndex = make(map[string][]string, zb0006)
			} else if len(z.NgramIndex) > 0 {
				clear(z.NgramIndex)
			}
			for zb0006 > 0 {
				var za0008 []string
				zb0006--
				var za0007 string
				za0007, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "NgramIndex")
					return
				}
				var zb0007 uint32
				zb0007, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "NgramIndex", za0007)
					return
				}
				if cap(za0008) >= int(zb0007) {
					za0008 = (za0008)[:zb0007]
				} else {
					za0008 = make([]string, zb0007)
				}
				for za0009 := range za0008 {
					za0008[za0009], bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "NgramIndex", za0007, za0009)
						return
					}
				}
				z.NgramIndex[za0007] = za0008
			}
		case "Inverted":
			var zb0008 uint32
			zb0008, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Inverted")
				return
			}
			if z.Inverted == nil {
				z.Inverted = make(map[string]map[string][]int, zb0008)
			} else if len(z.Inverted) > 0 {
				clear(z.Inverted)
			}
			for zb0008 > 0 {
				var za0011 map[string][]int
				zb0008--
				var za0010 string
				za0010, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Inverted")
					return
				}
				var zb0009 uint32
				zb0009, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Inverted", za0010)
					return
				}
				if za0011 == nil {
					za0011 = make(map[string][]int, zb0009)
				} else if len(za0011) > 0 {
					clear(za0011)
				}
				for zb0009 > 0 {
					var za0013 []int
					zb0009--
					var za0012 string
					za0012, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Inverted", za0010)
						return
					}
					var zb0010 uint32
					zb0010, bts, err = msgp.ReadArrayHeaderBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Inverted", za0010, za0012)
						return
					}
					if cap(za0013) >= int(zb0010) {
						za0013 = (za0013)[:zb0010]
					} else {
						za0013 = make([]int, zb0010)
					}
					for za0014 := range za0013 {
						za0013[za0014], bts, err = msgp.ReadIntBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Inverted", za0010, za0012, za0014)
							return
						}
					}
					za0011[za0012] = za0013
				}
				z.Inverted[za0010] = za0011
			}
		case "Offsets":
			var zb0011 uint32
			zb0011, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Offsets")
				return
			}
			if z.Offsets == nil {
				z.Offsets = make(map[string]map[string][]int, zb0011)
			} else if len(z.Offsets) > 0 {
				clear(z.Offsets)
			}
			for zb0011 > 0 {
				var za0016 map[string][]int
				zb0011--
				var za0015 string
				za0015, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Offsets")
					return
				}
				var zb0012 uint32
				zb0012, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Offsets", za0015)
					return
				}
				if za0016 == nil {
					za0016 = make(map[string][]int, zb0012)
				} else if len(za0016) > 0 {
					clear(za0016)
				}
				for zb0012 > 0 {
					var za0018 []int
					zb0012--
					var za0017 string
					za0017, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Offsets", za0015)
						return
					}
					var zb0013 uint32
					zb0013, bts, err = msgp.ReadArrayHeaderBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Offsets", za0015, za0017)
						return
					}
					if cap(za0018) >= int(zb0013) {
						za0018 = (za0018)[:zb0013]
					} else {
						za0018 = make([]int, zb0013)
					}
					for za0019 := range za0018 {
						za0018[za0019], bts, err = msgp.ReadIntBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Offsets", za0015, za0017, za0019)
							return
						}
					}
					za0016[za0017] = za0018
				}
				z.Offsets[za0015] = za0016
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SearchIndex) Msgsize() (s int) {
	s = 1 + 14 + msgp.Int64Size + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Posts {
		s += z.Posts[za0001].Msgsize()
	}
	s += 8 + msgp.MapHeaderSize
	if z.DocLens != nil {
		for za0002, za0003 := range z.DocLens {
			_ = za0003
			s += msgp.StringPrefixSize + len(za0002) + msgp.Int64Size
		}
	}
	s += 10 + msgp.Float64Size + 10 + msgp.Int64Size + 8 + msgp.MapHeaderSize
	if z.StemMap != nil {
		for za0004, za0005 := range z.StemMap {
			_ = za0005
			s += msgp.StringPrefixSize + len(za0004) + msgp.ArrayHeaderSize
			for za0006 := range za0005 {
				s += msgp.StringPrefixSize + len(za0005[za0006])
			}
		}
	}
	s += 11 + msgp.MapHeaderSize
	if z.NgramIndex != nil {
		for za0007, za0008 := range z.NgramIndex {
			_ = za0008
			s += msgp.StringPrefixSize + len(za0007) + msgp.ArrayHeaderSize
			for za0009 := range za0008 {
				s += msgp.StringPrefixSize + len(za0008[za0009])
			}
		}
	}
	s += 9 + msgp.MapHeaderSize
	if z.Inverted != nil {
		for za0010, za0011 := range z.Inverted {
			_ = za0011
			s += msgp.StringPrefixSize + len(za0010) + msgp.MapHeaderSize
			if za0011 != nil {
				for za0012, za0013 := range za0011 {
					_ = za0013
					s += msgp.StringPrefixSize + len(za0012) + msgp.ArrayHeaderSize + (len(za0013) * (msgp.IntSize))
				}
			}
		}
	}
	s += 8 + msgp.MapHeaderSize
	if z.Offsets != nil {
		for za0015, za0016 := range z.Offsets {
			_ = za0016
			s += msgp.StringPrefixSize + len(za0015) + msgp.MapHeaderSize
			if za0016 != nil {
				for za0017, za0018 := range za0016 {
					_ = za0018
					s += msgp.StringPrefixSize + len(za0017) + msgp.ArrayHeaderSize + (len(za0018) * (msgp.IntSize))
				}
			}
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TOCEntry) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Text":
			z.Text, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Text")
				return
			}
		case "Level":
			z.Level, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Level")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z TOCEntry) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "ID"
	err = en.Append(0x83, 0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "Text"
	err = en.Append(0xa4, 0x54, 0x65, 0x78, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Text)
	if err != nil {
		err = msgp.WrapError(err, "Text")
		return
	}
	// write "Level"
	err = en.Append(0xa5, 0x4c, 0x65, 0x76, 0x65, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Level)
	if err != nil {
		err = msgp.WrapError(err, "Level")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z TOCEntry) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "ID"
	o = append(o, 0x83, 0xa2, 0x49, 0x44)
	o = msgp.AppendString(o, z.ID)
	// string "Text"
	o = append(o, 0xa4, 0x54, 0x65, 0x78, 0x74)
	o = msgp.AppendString(o, z.Text)
	// string "Level"
	o = append(o, 0xa5, 0x4c, 0x65, 0x76, 0x65, 0x6c)
	o = msgp.AppendInt(o, z.Level)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TOCEntry) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Text":
			z.Text, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Text")
				return
			}
		case "Level":
			z.Level, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Level")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z TOCEntry) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 5 + msgp.StringPrefixSize + len(z.Text) + 6 + msgp.IntSize
	return
}
