// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package models

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Paginator) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "CurrentPage":
			z.CurrentPage, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "CurrentPage")
				return
			}
		case "TotalPages":
			z.TotalPages, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "TotalPages")
				return
			}
		case "PrevURL":
			z.PrevURL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PrevURL")
				return
			}
		case "NextURL":
			z.NextURL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "NextURL")
				return
			}
		case "FirstURL":
			z.FirstURL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "FirstURL")
				return
			}
		case "LastURL":
			z.LastURL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "LastURL")
				return
			}
		case "HasPrev":
			z.HasPrev, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "HasPrev")
				return
			}
		case "HasNext":
			z.HasNext, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "HasNext")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Paginator) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 8
	// write "CurrentPage"
	err = en.Append(0x88, 0xab, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.CurrentPage)
	if err != nil {
		err = msgp.WrapError(err, "CurrentPage")
		return
	}
	// write "TotalPages"
	err = en.Append(0xaa, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.TotalPages)
	if err != nil {
		err = msgp.WrapError(err, "TotalPages")
		return
	}
	// write "PrevURL"
	err = en.Append(0xa7, 0x50, 0x72, 0x65, 0x76, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.PrevURL)
	if err != nil {
		err = msgp.WrapError(err, "PrevURL")
		return
	}
	// write "NextURL"
	err = en.Append(0xa7, 0x4e, 0x65, 0x78, 0x74, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.NextURL)
	if err != nil {
		err = msgp.WrapError(err, "NextURL")
		return
	}
	// write "FirstURL"
	err = en.Append(0xa8, 0x46, 0x69, 0x72, 0x73, 0x74, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.FirstURL)
	if err != nil {
		err = msgp.WrapError(err, "FirstURL")
		return
	}
	// write "LastURL"
	err = en.Append(0xa7, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x52, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteString(z.LastURL)
	if err != nil {
		err = msgp.WrapError(err, "LastURL")
		return
	}
	// write "HasPrev"
	err = en.Append(0xa7, 0x48, 0x61, 0x73, 0x50, 0x72, 0x65, 0x76)
	if err != nil {
		return
	}
	err = en.WriteBool(z.HasPrev)
	if err != nil {
		err = msgp.WrapError(err, "HasPrev")
		return
	}
	// write "HasNext"
	err = en.Append(0xa7, 0x48, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBool(z.HasNext)
	if err != nil {
		err = msgp.WrapError(err, "HasNext")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Paginator) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 8
	// string "CurrentPage"
	o = append(o, 0x88, 0xab, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65)
	o = msgp.AppendInt(o, z.CurrentPage)
	// string "TotalPages"
	o = append(o, 0xaa, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73)
	o = msgp.AppendInt(o, z.TotalPages)
	// string "PrevURL"
	o = append(o, 0xa7, 0x50, 0x72, 0x65, 0x76, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.PrevURL)
	// string "NextURL"
	o = append(o, 0xa7, 0x4e, 0x65, 0x78, 0x74, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.NextURL)
	// string "FirstURL"
	o = append(o, 0xa8, 0x46, 0x69, 0x72, 0x73, 0x74, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.FirstURL)
	// string "LastURL"
	o = append(o, 0xa7, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x52, 0x4c)
	o = msgp.AppendString(o, z.LastURL)
	// string "HasPrev"
	o = append(o, 0xa7, 0x48, 0x61, 0x73, 0x50, 0x72, 0x65, 0x76)
	o = msgp.AppendBool(o, z.HasPrev)
	// string "HasNext"
	o = append(o, 0xa7, 0x48, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74)
	o = msgp.AppendBool(o, z.HasNext)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Paginator) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "CurrentPage":
			z.CurrentPage, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CurrentPage")
				return
			}
		case "TotalPages":
			z.TotalPages, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalPages")
				return
			}
		case "PrevURL":
			z.PrevURL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PrevURL")
				return
			}
		case "NextURL":
			z.NextURL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NextURL")
				return
			}
		case "FirstURL":
			z.FirstURL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FirstURL")
				return
			}
		case "LastURL":
			z.LastURL, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastURL")
				return
			}
		case "HasPrev":
			z.HasPrev, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "HasPrev")
				return
			}
		case "HasNext":
			z.HasNext, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "HasNext")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Paginator) Msgsize() (s int) {
	s = 1 + 12 + msgp.IntSize + 11 + msgp.IntSize + 8 + msgp.StringPrefixSize + len(z.PrevURL) + 8 + msgp.StringPrefixSize + len(z.NextURL) + 9 + msgp.StringPrefixSize + len(z.FirstURL) + 8 + msgp.StringPrefixSize + len(z.LastURL) + 8 + msgp.BoolSize + 8 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TOCEntry) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Text":
			z.Text, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Text")
				return
			}
		case "Level":
			z.Level, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Level")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z TOCEntry) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "ID"
	err = en.Append(0x83, 0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "Text"
	err = en.Append(0xa4, 0x54, 0x65, 0x78, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Text)
	if err != nil {
		err = msgp.WrapError(err, "Text")
		return
	}
	// write "Level"
	err = en.Append(0xa5, 0x4c, 0x65, 0x76, 0x65, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Level)
	if err != nil {
		err = msgp.WrapError(err, "Level")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z TOCEntry) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "ID"
	o = append(o, 0x83, 0xa2, 0x49, 0x44)
	o = msgp.AppendString(o, z.ID)
	// string "Text"
	o = append(o, 0xa4, 0x54, 0x65, 0x78, 0x74)
	o = msgp.AppendString(o, z.Text)
	// string "Level"
	o = append(o, 0xa5, 0x4c, 0x65, 0x76, 0x65, 0x6c)
	o = msgp.AppendInt(o, z.Level)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TOCEntry) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Text":
			z.Text, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Text")
				return
			}
		case "Level":
			z.Level, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Level")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z TOCEntry) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 5 + msgp.StringPrefixSize + len(z.Text) + 6 + msgp.IntSize
	return
}
