// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package models

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *MathExpression) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "latex":
			z.LaTeX, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "LaTeX")
				return
			}
		case "displayMode":
			z.DisplayMode, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "DisplayMode")
				return
			}
		case "hash":
			z.Hash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MathExpression) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "latex"
	err = en.Append(0x83, 0xa5, 0x6c, 0x61, 0x74, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteString(z.LaTeX)
	if err != nil {
		err = msgp.WrapError(err, "LaTeX")
		return
	}
	// write "displayMode"
	err = en.Append(0xab, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBool(z.DisplayMode)
	if err != nil {
		err = msgp.WrapError(err, "DisplayMode")
		return
	}
	// write "hash"
	err = en.Append(0xa4, 0x68, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Hash)
	if err != nil {
		err = msgp.WrapError(err, "Hash")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z MathExpression) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "latex"
	o = append(o, 0x83, 0xa5, 0x6c, 0x61, 0x74, 0x65, 0x78)
	o = msgp.AppendString(o, z.LaTeX)
	// string "displayMode"
	o = append(o, 0xab, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65)
	o = msgp.AppendBool(o, z.DisplayMode)
	// string "hash"
	o = append(o, 0xa4, 0x68, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.Hash)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MathExpression) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "latex":
			z.LaTeX, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LaTeX")
				return
			}
		case "displayMode":
			z.DisplayMode, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DisplayMode")
				return
			}
		case "hash":
			z.Hash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MathExpression) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.LaTeX) + 12 + msgp.BoolSize + 5 + msgp.StringPrefixSize + len(z.Hash)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SSRArtifactType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int
		zb0001, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = SSRArtifactType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z SSRArtifactType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt(int(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z SSRArtifactType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt(o, int(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SSRArtifactType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int
		zb0001, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = SSRArtifactType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z SSRArtifactType) Msgsize() (s int) {
	s = msgp.IntSize
	return
}
