package orchestration

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"golang.org/x/sync/errgroup"

	"github.com/Kush-Singh-26/kosh/builder/cache"
	"github.com/Kush-Singh-26/kosh/builder/generators"
	"github.com/Kush-Singh-26/kosh/builder/utils/timeutil"

	"github.com/spf13/afero"
)

const (
	pwaCacheDirMode  = 0755
	pwaCacheFileMode = 0644
	pwaIconSmall     = 192
	pwaIconLarge     = 512
)

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func shouldGeneratePWAIcons(shouldForce, hasHashFile, hasCache192, hasCache512 bool) bool {
	return shouldForce || !hasHashFile || !hasCache192 || !hasCache512
}

func (b *Engine) generatePWA(ctx context.Context, shouldForce bool) error {
	if b.Cfg.IsDev {
		return nil
	}

	g, _ := errgroup.WithContext(ctx)

	g.Go(func() error {
		return generators.GenerateSW(generators.SWOptions{
			Sink:         b.Sink,
			DestDir:      b.Cfg.OutputDir,
			BuildVersion: b.Cfg.BuildVersion,
			ForceRebuild: shouldForce,
			BaseURL:      b.Cfg.BaseURL,
			Assets:       b.Deps.Render.GetAssets(),
			IsTesting:    b.Ctx.IsTesting,
		})
	})

	g.Go(func() error {
		return generators.GenerateManifest(generators.ManifestOptions{
			Sink:            b.Sink,
			DestDir:         b.Cfg.OutputDir,
			BaseURL:         b.Cfg.BaseURL,
			SiteTitle:       b.Cfg.Title,
			SiteDescription: b.Cfg.Description,
			ForceRebuild:    shouldForce,
			IsTesting:       b.Ctx.IsTesting,
		})
	})

	g.Go(func() error {
		iconTimer := timeutil.StartPhase("PWA icons")
		defer iconTimer.Stop()

		logoPath := b.getLogoPath()
		if logoPath == "" {
			return nil
		}

		// Ensure info is available
		exists, _ := afero.Exists(b.Deps.SourceFs, logoPath)
		if !exists {
			return nil
		}
		srcInfo, _ := b.Deps.SourceFs.Stat(logoPath)

		// Calculate hash based on logo mtime and size
		hashContent := fmt.Sprintf("%s-%d-%d", logoPath, srcInfo.Size(), srcInfo.ModTime().UnixNano())
		currentHash := cache.HashString(hashContent)

		// Check cache
		cacheDir := filepath.Join(b.Cfg.CacheDir, "pwa-icons")
		cacheHashFile := filepath.Join(cacheDir, currentHash+".hash")
		cache192 := filepath.Join(cacheDir, fmt.Sprintf("%s-%d.png", currentHash, pwaIconSmall))
		cache512 := filepath.Join(cacheDir, fmt.Sprintf("%s-%d.png", currentHash, pwaIconLarge))

		hasHashFile := fileExists(cacheHashFile)
		hasCache192 := fileExists(cache192)
		hasCache512 := fileExists(cache512)

		// Generate if forced or cache is not fully available.
		needsGeneration := shouldGeneratePWAIcons(shouldForce, hasHashFile, hasCache192, hasCache512)

		if needsGeneration {
			// Generate icons to memory once, then write to both sink and cache.
			icons, err := generators.GeneratePWAIconBytes(b.Deps.SourceFs, logoPath, b.Deps.Logger)
			if err == nil {
				if wErr := generators.WritePWAIcons(b.Sink, filepath.Join(b.Cfg.OutputDir, "static/images"), icons); wErr == nil {
					b.Deps.Render.RegisterFile(filepath.Join(b.Cfg.OutputDir, "static/images/icon-192.png"))
					b.Deps.Render.RegisterFile(filepath.Join(b.Cfg.OutputDir, "static/images/icon-512.png"))
				}

				_ = os.MkdirAll(cacheDir, pwaCacheDirMode)
				// Save hash to cache
				_ = os.WriteFile(cacheHashFile, []byte(currentHash), pwaCacheFileMode)

				// Persist generated bytes to cache for future reuse
				if data, ok := icons[pwaIconSmall]; ok {
					_ = os.WriteFile(cache192, data, pwaCacheFileMode)
				}
				if data, ok := icons[pwaIconLarge]; ok {
					_ = os.WriteFile(cache512, data, pwaCacheFileMode)
				}
			}
		} else {
			// Copy from cache to destination
			// Copy cached icons to VFS
			if data, err := os.ReadFile(cache192); err == nil {
				iconPath := filepath.Join(b.Cfg.OutputDir, "static/images/icon-192.png")
				_ = b.Sink.WriteFile(iconPath, data)
				b.Deps.Render.RegisterFile(iconPath)
			}
			if data, err := os.ReadFile(cache512); err == nil {
				iconPath := filepath.Join(b.Cfg.OutputDir, "static/images/icon-512.png")
				_ = b.Sink.WriteFile(iconPath, data)
				b.Deps.Render.RegisterFile(iconPath)
			}
		}
		return nil
	})

	return g.Wait()
}
