//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"context"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"

	"github.com/andybalholm/brotli"
	"github.com/zeebo/xxh3"
)

func main() {
	_, filename, _, _ := runtime.Caller(0)
	repoRoot := filepath.Clean(filepath.Join(filepath.Dir(filename), ".."))

	log.Printf("Rebuilding Search WASM in %s...", repoRoot)

	// 1. Compile WASM
	cmdSearch := filepath.Join(repoRoot, "cmd", "search")
	wasmDest := filepath.Join(repoRoot, ".kosh-cache", "wasm", "rebuild_temp.wasm")
	_ = os.MkdirAll(filepath.Dir(wasmDest), 0755)

	log.Printf("Compiling %s -> %s...", cmdSearch, wasmDest)

	// Try TinyGo first if available
	var cmd *exec.Cmd
	tinygoPath, _ := exec.LookPath("tinygo")
	if tinygoPath != "" {
		log.Printf("Using TinyGo for optimized WASM...")
		cmd = exec.CommandContext(context.Background(), tinygoPath, "build", "-o", wasmDest, "-target=wasm", cmdSearch)
	} else {
		log.Printf("TinyGo not found, falling back to standard Go...")
		cmd = exec.CommandContext(context.Background(), "go", "build", "-ldflags=-s -w", "-o", wasmDest, cmdSearch)
		cmd.Env = append(os.Environ(), "GOOS=js", "GOARCH=wasm", "CGO_ENABLED=0")
	}

	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		log.Fatalf("Failed to compile WASM: %v", err)
	}

	// 2. Compress with Brotli Best
	data, err := os.ReadFile(wasmDest)
	if err != nil {
		log.Fatalf("Failed to read built WASM: %v", err)
	}

	log.Printf("Compressing WASM (Brotli Best)...")
	var buf bytes.Buffer
	bw := brotli.NewWriterLevel(&buf, brotli.BestCompression)
	if _, err := bw.Write(data); err != nil {
		log.Fatalf("Compression failed: %v", err)
	}
	bw.Close()

	brDest := filepath.Join(repoRoot, "builder", "assets", "wasm", "search.wasm.br")
	_ = os.MkdirAll(filepath.Dir(brDest), 0755)
	if err := os.WriteFile(brDest, buf.Bytes(), 0644); err != nil {
		log.Fatalf("Failed to write compressed WASM: %v", err)
	}

	// 3. Calculate hashes
	binaryHash := hashBytes(data)
	sourceHash, err := calculateSourceHash(repoRoot)
	if err != nil {
		log.Fatalf("Failed to calculate source hash: %v", err)
	}

	// 4. Update builder/assets/search_hash.go
	hashGoDest := filepath.Join(repoRoot, "builder", "assets", "search_hash.go")
	hashGoContent := fmt.Sprintf(`// Code generated by scripts/rebuild_search.go; DO NOT EDIT.
package assets

// SearchWasmHash is the XXH3 hash of the uncompressed search.wasm binary
const SearchWasmHash = "%s"

// SearchSourceHash is the XXH3 hash of the search source code at the time of rebuild
const SearchSourceHash = "%s"
`, binaryHash, sourceHash)

	if err := os.WriteFile(hashGoDest, []byte(hashGoContent), 0644); err != nil {
		log.Fatalf("Failed to write search_hash.go: %v", err)
	}

	// 5. Cleanup
	_ = os.Remove(wasmDest)

	log.Printf("Successfully updated Search WASM assets.")
	log.Printf("Binary Hash: %s", binaryHash)
	log.Printf("Source Hash: %s", sourceHash)
	log.Printf("IMPORTANT: Re-install Kosh to apply changes: go install ./cmd/kosh")
}

func hashBytes(data []byte) string {
	hasher := xxh3.New()
	_, _ = hasher.Write(data)
	sum := hasher.Sum128()
	hb := sum.Bytes()
	return hex.EncodeToString(hb[:8])
}

func calculateSourceHash(repoRoot string) (string, error) {
	searchPaths := []string{
		filepath.Join(repoRoot, "cmd", "search"),
		filepath.Join(repoRoot, "builder", "search"),
		filepath.Join(repoRoot, "builder", "models"),
	}

	hasher := xxh3.New()
	var files []string
	for _, p := range searchPaths {
		_ = filepath.Walk(p, func(path string, info os.FileInfo, err error) error {
			if err == nil && !info.IsDir() && filepath.Ext(path) == ".go" {
				files = append(files, path)
			}
			return nil
		})
	}
	sort.Strings(files)

	for _, file := range files {
		f, err := os.Open(file)
		if err != nil {
			continue
		}
		_, _ = io.Copy(hasher, f)
		f.Close()
	}

	sum := hasher.Sum128()
	hb := sum.Bytes()
	return hex.EncodeToString(hb[:8]), nil
}
