package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"

	"github.com/andybalholm/brotli"
	"github.com/zeebo/xxh3"
)

const (
	wasmDirMode   = 0755
	wasmFileMode  = 0644
	wasmHashBytes = 8
	bytesPerKiB   = 1024
)

func main() {
	// 1. Setup paths
	repoRoot, err := getRepoRoot()
	if err != nil {
		fmt.Printf("Error finding repo root: %v\n", err)
		os.Exit(1)
	}

	cmdSearch := filepath.Join(repoRoot, "cmd", "search")
	wasmDest := filepath.Join(repoRoot, "search.wasm")
	brDest := filepath.Join(repoRoot, "builder", "assets", "wasm", "search.wasm.br")
	hashGoDest := filepath.Join(repoRoot, "builder", "assets", "search_hash.go")

	fmt.Printf("Building Search WASM...\n")

	// 2. Build WASM
	cmd := exec.Command("go", "build", "-o", wasmDest, cmdSearch)
	cmd.Env = append(os.Environ(), "GOOS=js", "GOARCH=wasm", "CGO_ENABLED=0")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		fmt.Printf("Build failed: %v\n", err)
		os.Exit(1)
	}

	// 3. Compress with Brotli
	fmt.Printf("Compressing with Brotli (Best Compression)...\n")
	data, err := os.ReadFile(wasmDest)
	if err != nil {
		fmt.Printf("Failed to read built WASM: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	bw := brotli.NewWriterLevel(&buf, brotli.BestCompression)
	if _, err := bw.Write(data); err != nil {
		fmt.Printf("Compression failed: %v\n", err)
		os.Exit(1)
	}
	if err := bw.Close(); err != nil {
		fmt.Printf("Failed to close Brotli writer: %v\n", err)
		os.Exit(1)
	}

	// 4. Write to builder/assets/wasm/
	if err := os.MkdirAll(filepath.Dir(brDest), wasmDirMode); err != nil {
		fmt.Printf("Failed to create destination directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(brDest, buf.Bytes(), wasmFileMode); err != nil {
		fmt.Printf("Failed to write compressed WASM: %v\n", err)
		os.Exit(1)
	}

	// 5. Calculate hash (XXH3 16-char hex)
	hash := hashBytes(data)

	// 6. Generate builder/assets/search_hash.go
	hashGoContent := fmt.Sprintf(`// Code generated by scripts/rebuild-search.go; DO NOT EDIT.
package assets

// SearchWasmHash is the XXH3 hash of the uncompressed search.wasm
const SearchWasmHash = "%s"
`, hash)

	if err := os.WriteFile(hashGoDest, []byte(hashGoContent), wasmFileMode); err != nil {
		fmt.Printf("Failed to write search_hash.go: %v\n", err)
		os.Exit(1)
	}

	// 7. Cleanup
	_ = os.Remove(wasmDest)

	fmt.Printf("Successfully rebuilt and compressed search engine!\n")
	fmt.Printf("  Uncompressed: %s\n", formatSize(len(data)))
	fmt.Printf("  Compressed:   %s\n", formatSize(buf.Len()))
	fmt.Printf("  Hash:         %s\n", hash)
	fmt.Printf("  Output Binary: %s\n", brDest)
	fmt.Printf("  Output Go:     %s\n", hashGoDest)
}

func hashBytes(data []byte) string {
	h := xxh3.New()
	_, _ = h.Write(data)
	sum := h.Sum128()
	b := sum.Bytes()
	return fmt.Sprintf("%x", b[:wasmHashBytes]) // 16 chars hex
}

func getRepoRoot() (string, error) {
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		return "", errors.New("could not get caller info")
	}
	// scripts/rebuild-search.go -> go back one level
	return filepath.Dir(filepath.Dir(filename)), nil
}

func formatSize(size int) string {
	return fmt.Sprintf("%.2f KB", float64(size)/bytesPerKiB)
}
