// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package searchpkg

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ContentRecord) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Title":
			z.Title, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "Link":
			z.Link, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Link")
				return
			}
		case "Description":
			z.Description, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Description")
				return
			}
		case "Taxonomies":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Taxonomies")
				return
			}
			if z.Taxonomies == nil {
				z.Taxonomies = make(map[string][]string, zb0002)
			} else if len(z.Taxonomies) > 0 {
				clear(z.Taxonomies)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Taxonomies")
					return
				}
				var za0002 []string
				var zb0003 uint32
				zb0003, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "Taxonomies", za0001)
					return
				}
				if cap(za0002) >= int(zb0003) {
					za0002 = (za0002)[:zb0003]
				} else {
					za0002 = make([]string, zb0003)
				}
				for za0003 := range za0002 {
					za0002[za0003], err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Taxonomies", za0001, za0003)
						return
					}
				}
				z.Taxonomies[za0001] = za0002
			}
		case "NormalizedTaxs":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "NormalizedTaxs")
				return
			}
			if z.NormalizedTaxs == nil {
				z.NormalizedTaxs = make(map[string][]string, zb0004)
			} else if len(z.NormalizedTaxs) > 0 {
				clear(z.NormalizedTaxs)
			}
			for zb0004 > 0 {
				zb0004--
				var za0004 string
				za0004, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "NormalizedTaxs")
					return
				}
				var za0005 []string
				var zb0005 uint32
				zb0005, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "NormalizedTaxs", za0004)
					return
				}
				if cap(za0005) >= int(zb0005) {
					za0005 = (za0005)[:zb0005]
				} else {
					za0005 = make([]string, zb0005)
				}
				for za0006 := range za0005 {
					za0005[za0006], err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "NormalizedTaxs", za0004, za0006)
						return
					}
				}
				z.NormalizedTaxs[za0004] = za0005
			}
		case "Content":
			z.Content, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "Date":
			z.Date, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Date")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ContentRecord) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "Title"
	err = en.Append(0x87, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Title)
	if err != nil {
		err = msgp.WrapError(err, "Title")
		return
	}
	// write "Link"
	err = en.Append(0xa4, 0x4c, 0x69, 0x6e, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteString(z.Link)
	if err != nil {
		err = msgp.WrapError(err, "Link")
		return
	}
	// write "Description"
	err = en.Append(0xab, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Description)
	if err != nil {
		err = msgp.WrapError(err, "Description")
		return
	}
	// write "Taxonomies"
	err = en.Append(0xaa, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x69, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Taxonomies)))
	if err != nil {
		err = msgp.WrapError(err, "Taxonomies")
		return
	}
	for za0001, za0002 := range z.Taxonomies {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Taxonomies")
			return
		}
		err = en.WriteArrayHeader(uint32(len(za0002)))
		if err != nil {
			err = msgp.WrapError(err, "Taxonomies", za0001)
			return
		}
		for za0003 := range za0002 {
			err = en.WriteString(za0002[za0003])
			if err != nil {
				err = msgp.WrapError(err, "Taxonomies", za0001, za0003)
				return
			}
		}
	}
	// write "NormalizedTaxs"
	err = en.Append(0xae, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x61, 0x78, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.NormalizedTaxs)))
	if err != nil {
		err = msgp.WrapError(err, "NormalizedTaxs")
		return
	}
	for za0004, za0005 := range z.NormalizedTaxs {
		err = en.WriteString(za0004)
		if err != nil {
			err = msgp.WrapError(err, "NormalizedTaxs")
			return
		}
		err = en.WriteArrayHeader(uint32(len(za0005)))
		if err != nil {
			err = msgp.WrapError(err, "NormalizedTaxs", za0004)
			return
		}
		for za0006 := range za0005 {
			err = en.WriteString(za0005[za0006])
			if err != nil {
				err = msgp.WrapError(err, "NormalizedTaxs", za0004, za0006)
				return
			}
		}
	}
	// write "Content"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Content)
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	// write "Date"
	err = en.Append(0xa4, 0x44, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Date)
	if err != nil {
		err = msgp.WrapError(err, "Date")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ContentRecord) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "Title"
	o = append(o, 0x87, 0xa5, 0x54, 0x69, 0x74, 0x6c, 0x65)
	o = msgp.AppendString(o, z.Title)
	// string "Link"
	o = append(o, 0xa4, 0x4c, 0x69, 0x6e, 0x6b)
	o = msgp.AppendString(o, z.Link)
	// string "Description"
	o = append(o, 0xab, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Description)
	// string "Taxonomies"
	o = append(o, 0xaa, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x69, 0x65, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Taxonomies)))
	for za0001, za0002 := range z.Taxonomies {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendArrayHeader(o, uint32(len(za0002)))
		for za0003 := range za0002 {
			o = msgp.AppendString(o, za0002[za0003])
		}
	}
	// string "NormalizedTaxs"
	o = append(o, 0xae, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x61, 0x78, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.NormalizedTaxs)))
	for za0004, za0005 := range z.NormalizedTaxs {
		o = msgp.AppendString(o, za0004)
		o = msgp.AppendArrayHeader(o, uint32(len(za0005)))
		for za0006 := range za0005 {
			o = msgp.AppendString(o, za0005[za0006])
		}
	}
	// string "Content"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	o = msgp.AppendString(o, z.Content)
	// string "Date"
	o = append(o, 0xa4, 0x44, 0x61, 0x74, 0x65)
	o = msgp.AppendInt64(o, z.Date)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ContentRecord) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Title":
			z.Title, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Title")
				return
			}
		case "Link":
			z.Link, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Link")
				return
			}
		case "Description":
			z.Description, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Description")
				return
			}
		case "Taxonomies":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Taxonomies")
				return
			}
			if z.Taxonomies == nil {
				z.Taxonomies = make(map[string][]string, zb0002)
			} else if len(z.Taxonomies) > 0 {
				clear(z.Taxonomies)
			}
			for zb0002 > 0 {
				var za0002 []string
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Taxonomies")
					return
				}
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Taxonomies", za0001)
					return
				}
				if cap(za0002) >= int(zb0003) {
					za0002 = (za0002)[:zb0003]
				} else {
					za0002 = make([]string, zb0003)
				}
				for za0003 := range za0002 {
					za0002[za0003], bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Taxonomies", za0001, za0003)
						return
					}
				}
				z.Taxonomies[za0001] = za0002
			}
		case "NormalizedTaxs":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NormalizedTaxs")
				return
			}
			if z.NormalizedTaxs == nil {
				z.NormalizedTaxs = make(map[string][]string, zb0004)
			} else if len(z.NormalizedTaxs) > 0 {
				clear(z.NormalizedTaxs)
			}
			for zb0004 > 0 {
				var za0005 []string
				zb0004--
				var za0004 string
				za0004, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "NormalizedTaxs")
					return
				}
				var zb0005 uint32
				zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "NormalizedTaxs", za0004)
					return
				}
				if cap(za0005) >= int(zb0005) {
					za0005 = (za0005)[:zb0005]
				} else {
					za0005 = make([]string, zb0005)
				}
				for za0006 := range za0005 {
					za0005[za0006], bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "NormalizedTaxs", za0004, za0006)
						return
					}
				}
				z.NormalizedTaxs[za0004] = za0005
			}
		case "Content":
			z.Content, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "Date":
			z.Date, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Date")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ContentRecord) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Title) + 5 + msgp.StringPrefixSize + len(z.Link) + 12 + msgp.StringPrefixSize + len(z.Description) + 11 + msgp.MapHeaderSize
	if z.Taxonomies != nil {
		for za0001, za0002 := range z.Taxonomies {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.ArrayHeaderSize
			for za0003 := range za0002 {
				s += msgp.StringPrefixSize + len(za0002[za0003])
			}
		}
	}
	s += 15 + msgp.MapHeaderSize
	if z.NormalizedTaxs != nil {
		for za0004, za0005 := range z.NormalizedTaxs {
			_ = za0005
			s += msgp.StringPrefixSize + len(za0004) + msgp.ArrayHeaderSize
			for za0006 := range za0005 {
				s += msgp.StringPrefixSize + len(za0005[za0006])
			}
		}
	}
	s += 8 + msgp.StringPrefixSize + len(z.Content) + 5 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *IndexedContent) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "DenseID":
			z.DenseID, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "DenseID")
				return
			}
		case "Record":
			err = z.Record.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Record")
				return
			}
		case "SourcePath":
			z.SourcePath, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SourcePath")
				return
			}
		case "WordFreqs":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "WordFreqs")
				return
			}
			if z.WordFreqs == nil {
				z.WordFreqs = make(map[string]int, zb0002)
			} else if len(z.WordFreqs) > 0 {
				clear(z.WordFreqs)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "WordFreqs")
					return
				}
				var za0002 int
				za0002, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "WordFreqs", za0001)
					return
				}
				z.WordFreqs[za0001] = za0002
			}
		case "DocLen":
			z.DocLen, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "DocLen")
				return
			}
		case "StemMap":
			var zb0003 uint32
			zb0003, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "StemMap")
				return
			}
			if z.StemMap == nil {
				z.StemMap = make(map[string]string, zb0003)
			} else if len(z.StemMap) > 0 {
				clear(z.StemMap)
			}
			for zb0003 > 0 {
				zb0003--
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "StemMap")
					return
				}
				var za0004 string
				za0004, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "StemMap", za0003)
					return
				}
				z.StemMap[za0003] = za0004
			}
		case "PositionalIndex":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "PositionalIndex")
				return
			}
			if z.PositionalIndex == nil {
				z.PositionalIndex = make(map[string][]uint32, zb0004)
			} else if len(z.PositionalIndex) > 0 {
				clear(z.PositionalIndex)
			}
			for zb0004 > 0 {
				zb0004--
				var za0005 string
				za0005, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex")
					return
				}
				var za0006 []uint32
				var zb0005 uint32
				zb0005, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex", za0005)
					return
				}
				if cap(za0006) >= int(zb0005) {
					za0006 = (za0006)[:zb0005]
				} else {
					za0006 = make([]uint32, zb0005)
				}
				for za0007 := range za0006 {
					za0006[za0007], err = dc.ReadUint32()
					if err != nil {
						err = msgp.WrapError(err, "PositionalIndex", za0005, za0007)
						return
					}
				}
				z.PositionalIndex[za0005] = za0006
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *IndexedContent) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "DenseID"
	err = en.Append(0x87, 0xa7, 0x44, 0x65, 0x6e, 0x73, 0x65, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.DenseID)
	if err != nil {
		err = msgp.WrapError(err, "DenseID")
		return
	}
	// write "Record"
	err = en.Append(0xa6, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64)
	if err != nil {
		return
	}
	err = z.Record.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Record")
		return
	}
	// write "SourcePath"
	err = en.Append(0xaa, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.SourcePath)
	if err != nil {
		err = msgp.WrapError(err, "SourcePath")
		return
	}
	// write "WordFreqs"
	err = en.Append(0xa9, 0x57, 0x6f, 0x72, 0x64, 0x46, 0x72, 0x65, 0x71, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.WordFreqs)))
	if err != nil {
		err = msgp.WrapError(err, "WordFreqs")
		return
	}
	for za0001, za0002 := range z.WordFreqs {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "WordFreqs")
			return
		}
		err = en.WriteInt(za0002)
		if err != nil {
			err = msgp.WrapError(err, "WordFreqs", za0001)
			return
		}
	}
	// write "DocLen"
	err = en.Append(0xa6, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt(z.DocLen)
	if err != nil {
		err = msgp.WrapError(err, "DocLen")
		return
	}
	// write "StemMap"
	err = en.Append(0xa7, 0x53, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.StemMap)))
	if err != nil {
		err = msgp.WrapError(err, "StemMap")
		return
	}
	for za0003, za0004 := range z.StemMap {
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "StemMap")
			return
		}
		err = en.WriteString(za0004)
		if err != nil {
			err = msgp.WrapError(err, "StemMap", za0003)
			return
		}
	}
	// write "PositionalIndex"
	err = en.Append(0xaf, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.PositionalIndex)))
	if err != nil {
		err = msgp.WrapError(err, "PositionalIndex")
		return
	}
	for za0005, za0006 := range z.PositionalIndex {
		err = en.WriteString(za0005)
		if err != nil {
			err = msgp.WrapError(err, "PositionalIndex")
			return
		}
		err = en.WriteArrayHeader(uint32(len(za0006)))
		if err != nil {
			err = msgp.WrapError(err, "PositionalIndex", za0005)
			return
		}
		for za0007 := range za0006 {
			err = en.WriteUint32(za0006[za0007])
			if err != nil {
				err = msgp.WrapError(err, "PositionalIndex", za0005, za0007)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *IndexedContent) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "DenseID"
	o = append(o, 0x87, 0xa7, 0x44, 0x65, 0x6e, 0x73, 0x65, 0x49, 0x44)
	o = msgp.AppendUint32(o, z.DenseID)
	// string "Record"
	o = append(o, 0xa6, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64)
	o, err = z.Record.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Record")
		return
	}
	// string "SourcePath"
	o = append(o, 0xaa, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68)
	o = msgp.AppendString(o, z.SourcePath)
	// string "WordFreqs"
	o = append(o, 0xa9, 0x57, 0x6f, 0x72, 0x64, 0x46, 0x72, 0x65, 0x71, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.WordFreqs)))
	for za0001, za0002 := range z.WordFreqs {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendInt(o, za0002)
	}
	// string "DocLen"
	o = append(o, 0xa6, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e)
	o = msgp.AppendInt(o, z.DocLen)
	// string "StemMap"
	o = append(o, 0xa7, 0x53, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x70)
	o = msgp.AppendMapHeader(o, uint32(len(z.StemMap)))
	for za0003, za0004 := range z.StemMap {
		o = msgp.AppendString(o, za0003)
		o = msgp.AppendString(o, za0004)
	}
	// string "PositionalIndex"
	o = append(o, 0xaf, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78)
	o = msgp.AppendMapHeader(o, uint32(len(z.PositionalIndex)))
	for za0005, za0006 := range z.PositionalIndex {
		o = msgp.AppendString(o, za0005)
		o = msgp.AppendArrayHeader(o, uint32(len(za0006)))
		for za0007 := range za0006 {
			o = msgp.AppendUint32(o, za0006[za0007])
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *IndexedContent) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "DenseID":
			z.DenseID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DenseID")
				return
			}
		case "Record":
			bts, err = z.Record.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Record")
				return
			}
		case "SourcePath":
			z.SourcePath, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SourcePath")
				return
			}
		case "WordFreqs":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WordFreqs")
				return
			}
			if z.WordFreqs == nil {
				z.WordFreqs = make(map[string]int, zb0002)
			} else if len(z.WordFreqs) > 0 {
				clear(z.WordFreqs)
			}
			for zb0002 > 0 {
				var za0002 int
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "WordFreqs")
					return
				}
				za0002, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "WordFreqs", za0001)
					return
				}
				z.WordFreqs[za0001] = za0002
			}
		case "DocLen":
			z.DocLen, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DocLen")
				return
			}
		case "StemMap":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StemMap")
				return
			}
			if z.StemMap == nil {
				z.StemMap = make(map[string]string, zb0003)
			} else if len(z.StemMap) > 0 {
				clear(z.StemMap)
			}
			for zb0003 > 0 {
				var za0004 string
				zb0003--
				var za0003 string
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StemMap")
					return
				}
				za0004, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StemMap", za0003)
					return
				}
				z.StemMap[za0003] = za0004
			}
		case "PositionalIndex":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PositionalIndex")
				return
			}
			if z.PositionalIndex == nil {
				z.PositionalIndex = make(map[string][]uint32, zb0004)
			} else if len(z.PositionalIndex) > 0 {
				clear(z.PositionalIndex)
			}
			for zb0004 > 0 {
				var za0006 []uint32
				zb0004--
				var za0005 string
				za0005, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex")
					return
				}
				var zb0005 uint32
				zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PositionalIndex", za0005)
					return
				}
				if cap(za0006) >= int(zb0005) {
					za0006 = (za0006)[:zb0005]
				} else {
					za0006 = make([]uint32, zb0005)
				}
				for za0007 := range za0006 {
					za0006[za0007], bts, err = msgp.ReadUint32Bytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "PositionalIndex", za0005, za0007)
						return
					}
				}
				z.PositionalIndex[za0005] = za0006
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *IndexedContent) Msgsize() (s int) {
	s = 1 + 8 + msgp.Uint32Size + 7 + z.Record.Msgsize() + 11 + msgp.StringPrefixSize + len(z.SourcePath) + 10 + msgp.MapHeaderSize
	if z.WordFreqs != nil {
		for za0001, za0002 := range z.WordFreqs {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.IntSize
		}
	}
	s += 7 + msgp.IntSize + 8 + msgp.MapHeaderSize
	if z.StemMap != nil {
		for za0003, za0004 := range z.StemMap {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.StringPrefixSize + len(za0004)
		}
	}
	s += 16 + msgp.MapHeaderSize
	if z.PositionalIndex != nil {
		for za0005, za0006 := range z.PositionalIndex {
			_ = za0006
			s += msgp.StringPrefixSize + len(za0005) + msgp.ArrayHeaderSize + (len(za0006) * (msgp.Uint32Size))
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SearchIndex) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SchemaVersion":
			z.SchemaVersion, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "SchemaVersion")
				return
			}
		case "Items":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Items")
				return
			}
			if cap(z.Items) >= int(zb0002) {
				z.Items = (z.Items)[:zb0002]
			} else {
				z.Items = make([]ContentRecord, zb0002)
			}
			for za0001 := range z.Items {
				err = z.Items[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Items", za0001)
					return
				}
			}
		case "ItemLens":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "ItemLens")
				return
			}
			if cap(z.ItemLens) >= int(zb0003) {
				z.ItemLens = (z.ItemLens)[:zb0003]
			} else {
				z.ItemLens = make([]int32, zb0003)
			}
			for za0002 := range z.ItemLens {
				z.ItemLens[za0002], err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "ItemLens", za0002)
					return
				}
			}
		case "AvgDocLen":
			z.AvgDocLen, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "AvgDocLen")
				return
			}
		case "TotalItems":
			z.TotalItems, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "TotalItems")
				return
			}
		case "Ranking":
			err = z.Ranking.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Ranking")
				return
			}
		case "StemMap":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "StemMap")
				return
			}
			if z.StemMap == nil {
				z.StemMap = make(map[string][]string, zb0004)
			} else if len(z.StemMap) > 0 {
				clear(z.StemMap)
			}
			for zb0004 > 0 {
				zb0004--
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "StemMap")
					return
				}
				var za0004 []string
				var zb0005 uint32
				zb0005, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "StemMap", za0003)
					return
				}
				if cap(za0004) >= int(zb0005) {
					za0004 = (za0004)[:zb0005]
				} else {
					za0004 = make([]string, zb0005)
				}
				for za0005 := range za0004 {
					za0004[za0005], err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "StemMap", za0003, za0005)
						return
					}
				}
				z.StemMap[za0003] = za0004
			}
		case "Terms":
			var zb0006 uint32
			zb0006, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Terms")
				return
			}
			if cap(z.Terms) >= int(zb0006) {
				z.Terms = (z.Terms)[:zb0006]
			} else {
				z.Terms = make([]string, zb0006)
			}
			for za0006 := range z.Terms {
				z.Terms[za0006], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Terms", za0006)
					return
				}
			}
		case "PostingOffsets":
			var zb0007 uint32
			zb0007, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "PostingOffsets")
				return
			}
			if cap(z.PostingOffsets) >= int(zb0007) {
				z.PostingOffsets = (z.PostingOffsets)[:zb0007]
			} else {
				z.PostingOffsets = make([]uint32, zb0007)
			}
			for za0007 := range z.PostingOffsets {
				z.PostingOffsets[za0007], err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "PostingOffsets", za0007)
					return
				}
			}
		case "DocIDs":
			var zb0008 uint32
			zb0008, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "DocIDs")
				return
			}
			if cap(z.DocIDs) >= int(zb0008) {
				z.DocIDs = (z.DocIDs)[:zb0008]
			} else {
				z.DocIDs = make([]uint32, zb0008)
			}
			for za0008 := range z.DocIDs {
				z.DocIDs[za0008], err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "DocIDs", za0008)
					return
				}
			}
		case "DocPosOffsets":
			var zb0009 uint32
			zb0009, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "DocPosOffsets")
				return
			}
			if cap(z.DocPosOffsets) >= int(zb0009) {
				z.DocPosOffsets = (z.DocPosOffsets)[:zb0009]
			} else {
				z.DocPosOffsets = make([]uint32, zb0009)
			}
			for za0009 := range z.DocPosOffsets {
				z.DocPosOffsets[za0009], err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "DocPosOffsets", za0009)
					return
				}
			}
		case "PosOffsets":
			var zb0010 uint32
			zb0010, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "PosOffsets")
				return
			}
			if cap(z.PosOffsets) >= int(zb0010) {
				z.PosOffsets = (z.PosOffsets)[:zb0010]
			} else {
				z.PosOffsets = make([]uint32, zb0010)
			}
			for za0010 := range z.PosOffsets {
				z.PosOffsets[za0010], err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "PosOffsets", za0010)
					return
				}
			}
		case "Positions":
			var zb0011 uint32
			zb0011, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Positions")
				return
			}
			if cap(z.Positions) >= int(zb0011) {
				z.Positions = (z.Positions)[:zb0011]
			} else {
				z.Positions = make([]uint32, zb0011)
			}
			for za0011 := range z.Positions {
				z.Positions[za0011], err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "Positions", za0011)
					return
				}
			}
		case "TitlePostingOffsets":
			var zb0012 uint32
			zb0012, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "TitlePostingOffsets")
				return
			}
			if cap(z.TitlePostingOffsets) >= int(zb0012) {
				z.TitlePostingOffsets = (z.TitlePostingOffsets)[:zb0012]
			} else {
				z.TitlePostingOffsets = make([]uint32, zb0012)
			}
			for za0012 := range z.TitlePostingOffsets {
				z.TitlePostingOffsets[za0012], err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "TitlePostingOffsets", za0012)
					return
				}
			}
		case "TitleDocIDs":
			var zb0013 uint32
			zb0013, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "TitleDocIDs")
				return
			}
			if cap(z.TitleDocIDs) >= int(zb0013) {
				z.TitleDocIDs = (z.TitleDocIDs)[:zb0013]
			} else {
				z.TitleDocIDs = make([]uint32, zb0013)
			}
			for za0013 := range z.TitleDocIDs {
				z.TitleDocIDs[za0013], err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "TitleDocIDs", za0013)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SearchIndex) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 15
	// write "SchemaVersion"
	err = en.Append(0x8f, 0xad, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.SchemaVersion)
	if err != nil {
		err = msgp.WrapError(err, "SchemaVersion")
		return
	}
	// write "Items"
	err = en.Append(0xa5, 0x49, 0x74, 0x65, 0x6d, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Items)))
	if err != nil {
		err = msgp.WrapError(err, "Items")
		return
	}
	for za0001 := range z.Items {
		err = z.Items[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Items", za0001)
			return
		}
	}
	// write "ItemLens"
	err = en.Append(0xa8, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x65, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.ItemLens)))
	if err != nil {
		err = msgp.WrapError(err, "ItemLens")
		return
	}
	for za0002 := range z.ItemLens {
		err = en.WriteInt32(z.ItemLens[za0002])
		if err != nil {
			err = msgp.WrapError(err, "ItemLens", za0002)
			return
		}
	}
	// write "AvgDocLen"
	err = en.Append(0xa9, 0x41, 0x76, 0x67, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.AvgDocLen)
	if err != nil {
		err = msgp.WrapError(err, "AvgDocLen")
		return
	}
	// write "TotalItems"
	err = en.Append(0xaa, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.TotalItems)
	if err != nil {
		err = msgp.WrapError(err, "TotalItems")
		return
	}
	// write "Ranking"
	err = en.Append(0xa7, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = z.Ranking.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Ranking")
		return
	}
	// write "StemMap"
	err = en.Append(0xa7, 0x53, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.StemMap)))
	if err != nil {
		err = msgp.WrapError(err, "StemMap")
		return
	}
	for za0003, za0004 := range z.StemMap {
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "StemMap")
			return
		}
		err = en.WriteArrayHeader(uint32(len(za0004)))
		if err != nil {
			err = msgp.WrapError(err, "StemMap", za0003)
			return
		}
		for za0005 := range za0004 {
			err = en.WriteString(za0004[za0005])
			if err != nil {
				err = msgp.WrapError(err, "StemMap", za0003, za0005)
				return
			}
		}
	}
	// write "Terms"
	err = en.Append(0xa5, 0x54, 0x65, 0x72, 0x6d, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Terms)))
	if err != nil {
		err = msgp.WrapError(err, "Terms")
		return
	}
	for za0006 := range z.Terms {
		err = en.WriteString(z.Terms[za0006])
		if err != nil {
			err = msgp.WrapError(err, "Terms", za0006)
			return
		}
	}
	// write "PostingOffsets"
	err = en.Append(0xae, 0x50, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.PostingOffsets)))
	if err != nil {
		err = msgp.WrapError(err, "PostingOffsets")
		return
	}
	for za0007 := range z.PostingOffsets {
		err = en.WriteUint32(z.PostingOffsets[za0007])
		if err != nil {
			err = msgp.WrapError(err, "PostingOffsets", za0007)
			return
		}
	}
	// write "DocIDs"
	err = en.Append(0xa6, 0x44, 0x6f, 0x63, 0x49, 0x44, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.DocIDs)))
	if err != nil {
		err = msgp.WrapError(err, "DocIDs")
		return
	}
	for za0008 := range z.DocIDs {
		err = en.WriteUint32(z.DocIDs[za0008])
		if err != nil {
			err = msgp.WrapError(err, "DocIDs", za0008)
			return
		}
	}
	// write "DocPosOffsets"
	err = en.Append(0xad, 0x44, 0x6f, 0x63, 0x50, 0x6f, 0x73, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.DocPosOffsets)))
	if err != nil {
		err = msgp.WrapError(err, "DocPosOffsets")
		return
	}
	for za0009 := range z.DocPosOffsets {
		err = en.WriteUint32(z.DocPosOffsets[za0009])
		if err != nil {
			err = msgp.WrapError(err, "DocPosOffsets", za0009)
			return
		}
	}
	// write "PosOffsets"
	err = en.Append(0xaa, 0x50, 0x6f, 0x73, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.PosOffsets)))
	if err != nil {
		err = msgp.WrapError(err, "PosOffsets")
		return
	}
	for za0010 := range z.PosOffsets {
		err = en.WriteUint32(z.PosOffsets[za0010])
		if err != nil {
			err = msgp.WrapError(err, "PosOffsets", za0010)
			return
		}
	}
	// write "Positions"
	err = en.Append(0xa9, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Positions)))
	if err != nil {
		err = msgp.WrapError(err, "Positions")
		return
	}
	for za0011 := range z.Positions {
		err = en.WriteUint32(z.Positions[za0011])
		if err != nil {
			err = msgp.WrapError(err, "Positions", za0011)
			return
		}
	}
	// write "TitlePostingOffsets"
	err = en.Append(0xb3, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.TitlePostingOffsets)))
	if err != nil {
		err = msgp.WrapError(err, "TitlePostingOffsets")
		return
	}
	for za0012 := range z.TitlePostingOffsets {
		err = en.WriteUint32(z.TitlePostingOffsets[za0012])
		if err != nil {
			err = msgp.WrapError(err, "TitlePostingOffsets", za0012)
			return
		}
	}
	// write "TitleDocIDs"
	err = en.Append(0xab, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x44, 0x6f, 0x63, 0x49, 0x44, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.TitleDocIDs)))
	if err != nil {
		err = msgp.WrapError(err, "TitleDocIDs")
		return
	}
	for za0013 := range z.TitleDocIDs {
		err = en.WriteUint32(z.TitleDocIDs[za0013])
		if err != nil {
			err = msgp.WrapError(err, "TitleDocIDs", za0013)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SearchIndex) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 15
	// string "SchemaVersion"
	o = append(o, 0x8f, 0xad, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendInt64(o, z.SchemaVersion)
	// string "Items"
	o = append(o, 0xa5, 0x49, 0x74, 0x65, 0x6d, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Items)))
	for za0001 := range z.Items {
		o, err = z.Items[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Items", za0001)
			return
		}
	}
	// string "ItemLens"
	o = append(o, 0xa8, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x65, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.ItemLens)))
	for za0002 := range z.ItemLens {
		o = msgp.AppendInt32(o, z.ItemLens[za0002])
	}
	// string "AvgDocLen"
	o = append(o, 0xa9, 0x41, 0x76, 0x67, 0x44, 0x6f, 0x63, 0x4c, 0x65, 0x6e)
	o = msgp.AppendFloat64(o, z.AvgDocLen)
	// string "TotalItems"
	o = append(o, 0xaa, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73)
	o = msgp.AppendInt64(o, z.TotalItems)
	// string "Ranking"
	o = append(o, 0xa7, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67)
	o, err = z.Ranking.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Ranking")
		return
	}
	// string "StemMap"
	o = append(o, 0xa7, 0x53, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x70)
	o = msgp.AppendMapHeader(o, uint32(len(z.StemMap)))
	for za0003, za0004 := range z.StemMap {
		o = msgp.AppendString(o, za0003)
		o = msgp.AppendArrayHeader(o, uint32(len(za0004)))
		for za0005 := range za0004 {
			o = msgp.AppendString(o, za0004[za0005])
		}
	}
	// string "Terms"
	o = append(o, 0xa5, 0x54, 0x65, 0x72, 0x6d, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Terms)))
	for za0006 := range z.Terms {
		o = msgp.AppendString(o, z.Terms[za0006])
	}
	// string "PostingOffsets"
	o = append(o, 0xae, 0x50, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.PostingOffsets)))
	for za0007 := range z.PostingOffsets {
		o = msgp.AppendUint32(o, z.PostingOffsets[za0007])
	}
	// string "DocIDs"
	o = append(o, 0xa6, 0x44, 0x6f, 0x63, 0x49, 0x44, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.DocIDs)))
	for za0008 := range z.DocIDs {
		o = msgp.AppendUint32(o, z.DocIDs[za0008])
	}
	// string "DocPosOffsets"
	o = append(o, 0xad, 0x44, 0x6f, 0x63, 0x50, 0x6f, 0x73, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.DocPosOffsets)))
	for za0009 := range z.DocPosOffsets {
		o = msgp.AppendUint32(o, z.DocPosOffsets[za0009])
	}
	// string "PosOffsets"
	o = append(o, 0xaa, 0x50, 0x6f, 0x73, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.PosOffsets)))
	for za0010 := range z.PosOffsets {
		o = msgp.AppendUint32(o, z.PosOffsets[za0010])
	}
	// string "Positions"
	o = append(o, 0xa9, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Positions)))
	for za0011 := range z.Positions {
		o = msgp.AppendUint32(o, z.Positions[za0011])
	}
	// string "TitlePostingOffsets"
	o = append(o, 0xb3, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.TitlePostingOffsets)))
	for za0012 := range z.TitlePostingOffsets {
		o = msgp.AppendUint32(o, z.TitlePostingOffsets[za0012])
	}
	// string "TitleDocIDs"
	o = append(o, 0xab, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x44, 0x6f, 0x63, 0x49, 0x44, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.TitleDocIDs)))
	for za0013 := range z.TitleDocIDs {
		o = msgp.AppendUint32(o, z.TitleDocIDs[za0013])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SearchIndex) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SchemaVersion":
			z.SchemaVersion, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SchemaVersion")
				return
			}
		case "Items":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Items")
				return
			}
			if cap(z.Items) >= int(zb0002) {
				z.Items = (z.Items)[:zb0002]
			} else {
				z.Items = make([]ContentRecord, zb0002)
			}
			for za0001 := range z.Items {
				bts, err = z.Items[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Items", za0001)
					return
				}
			}
		case "ItemLens":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ItemLens")
				return
			}
			if cap(z.ItemLens) >= int(zb0003) {
				z.ItemLens = (z.ItemLens)[:zb0003]
			} else {
				z.ItemLens = make([]int32, zb0003)
			}
			for za0002 := range z.ItemLens {
				z.ItemLens[za0002], bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ItemLens", za0002)
					return
				}
			}
		case "AvgDocLen":
			z.AvgDocLen, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AvgDocLen")
				return
			}
		case "TotalItems":
			z.TotalItems, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalItems")
				return
			}
		case "Ranking":
			bts, err = z.Ranking.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ranking")
				return
			}
		case "StemMap":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StemMap")
				return
			}
			if z.StemMap == nil {
				z.StemMap = make(map[string][]string, zb0004)
			} else if len(z.StemMap) > 0 {
				clear(z.StemMap)
			}
			for zb0004 > 0 {
				var za0004 []string
				zb0004--
				var za0003 string
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StemMap")
					return
				}
				var zb0005 uint32
				zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StemMap", za0003)
					return
				}
				if cap(za0004) >= int(zb0005) {
					za0004 = (za0004)[:zb0005]
				} else {
					za0004 = make([]string, zb0005)
				}
				for za0005 := range za0004 {
					za0004[za0005], bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "StemMap", za0003, za0005)
						return
					}
				}
				z.StemMap[za0003] = za0004
			}
		case "Terms":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Terms")
				return
			}
			if cap(z.Terms) >= int(zb0006) {
				z.Terms = (z.Terms)[:zb0006]
			} else {
				z.Terms = make([]string, zb0006)
			}
			for za0006 := range z.Terms {
				z.Terms[za0006], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Terms", za0006)
					return
				}
			}
		case "PostingOffsets":
			var zb0007 uint32
			zb0007, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PostingOffsets")
				return
			}
			if cap(z.PostingOffsets) >= int(zb0007) {
				z.PostingOffsets = (z.PostingOffsets)[:zb0007]
			} else {
				z.PostingOffsets = make([]uint32, zb0007)
			}
			for za0007 := range z.PostingOffsets {
				z.PostingOffsets[za0007], bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PostingOffsets", za0007)
					return
				}
			}
		case "DocIDs":
			var zb0008 uint32
			zb0008, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DocIDs")
				return
			}
			if cap(z.DocIDs) >= int(zb0008) {
				z.DocIDs = (z.DocIDs)[:zb0008]
			} else {
				z.DocIDs = make([]uint32, zb0008)
			}
			for za0008 := range z.DocIDs {
				z.DocIDs[za0008], bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "DocIDs", za0008)
					return
				}
			}
		case "DocPosOffsets":
			var zb0009 uint32
			zb0009, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DocPosOffsets")
				return
			}
			if cap(z.DocPosOffsets) >= int(zb0009) {
				z.DocPosOffsets = (z.DocPosOffsets)[:zb0009]
			} else {
				z.DocPosOffsets = make([]uint32, zb0009)
			}
			for za0009 := range z.DocPosOffsets {
				z.DocPosOffsets[za0009], bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "DocPosOffsets", za0009)
					return
				}
			}
		case "PosOffsets":
			var zb0010 uint32
			zb0010, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PosOffsets")
				return
			}
			if cap(z.PosOffsets) >= int(zb0010) {
				z.PosOffsets = (z.PosOffsets)[:zb0010]
			} else {
				z.PosOffsets = make([]uint32, zb0010)
			}
			for za0010 := range z.PosOffsets {
				z.PosOffsets[za0010], bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PosOffsets", za0010)
					return
				}
			}
		case "Positions":
			var zb0011 uint32
			zb0011, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Positions")
				return
			}
			if cap(z.Positions) >= int(zb0011) {
				z.Positions = (z.Positions)[:zb0011]
			} else {
				z.Positions = make([]uint32, zb0011)
			}
			for za0011 := range z.Positions {
				z.Positions[za0011], bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Positions", za0011)
					return
				}
			}
		case "TitlePostingOffsets":
			var zb0012 uint32
			zb0012, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TitlePostingOffsets")
				return
			}
			if cap(z.TitlePostingOffsets) >= int(zb0012) {
				z.TitlePostingOffsets = (z.TitlePostingOffsets)[:zb0012]
			} else {
				z.TitlePostingOffsets = make([]uint32, zb0012)
			}
			for za0012 := range z.TitlePostingOffsets {
				z.TitlePostingOffsets[za0012], bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "TitlePostingOffsets", za0012)
					return
				}
			}
		case "TitleDocIDs":
			var zb0013 uint32
			zb0013, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TitleDocIDs")
				return
			}
			if cap(z.TitleDocIDs) >= int(zb0013) {
				z.TitleDocIDs = (z.TitleDocIDs)[:zb0013]
			} else {
				z.TitleDocIDs = make([]uint32, zb0013)
			}
			for za0013 := range z.TitleDocIDs {
				z.TitleDocIDs[za0013], bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "TitleDocIDs", za0013)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SearchIndex) Msgsize() (s int) {
	s = 1 + 14 + msgp.Int64Size + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Items {
		s += z.Items[za0001].Msgsize()
	}
	s += 9 + msgp.ArrayHeaderSize + (len(z.ItemLens) * (msgp.Int32Size)) + 10 + msgp.Float64Size + 11 + msgp.Int64Size + 8 + z.Ranking.Msgsize() + 8 + msgp.MapHeaderSize
	if z.StemMap != nil {
		for za0003, za0004 := range z.StemMap {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.ArrayHeaderSize
			for za0005 := range za0004 {
				s += msgp.StringPrefixSize + len(za0004[za0005])
			}
		}
	}
	s += 6 + msgp.ArrayHeaderSize
	for za0006 := range z.Terms {
		s += msgp.StringPrefixSize + len(z.Terms[za0006])
	}
	s += 15 + msgp.ArrayHeaderSize + (len(z.PostingOffsets) * (msgp.Uint32Size)) + 7 + msgp.ArrayHeaderSize + (len(z.DocIDs) * (msgp.Uint32Size)) + 14 + msgp.ArrayHeaderSize + (len(z.DocPosOffsets) * (msgp.Uint32Size)) + 11 + msgp.ArrayHeaderSize + (len(z.PosOffsets) * (msgp.Uint32Size)) + 10 + msgp.ArrayHeaderSize + (len(z.Positions) * (msgp.Uint32Size)) + 20 + msgp.ArrayHeaderSize + (len(z.TitlePostingOffsets) * (msgp.Uint32Size)) + 12 + msgp.ArrayHeaderSize + (len(z.TitleDocIDs) * (msgp.Uint32Size))
	return
}
